### ISSUE TITLE
Table Scrolling Design v2

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#115]
Right now, if a table is too wide, we allow it to scroll horizontally, but give no indication that this is possible (aside from the browser/OS's hinting scroll bar). Further, when a table is very long, the table header scrolls out of view.

Possible solutions that have been discussed have been to display some sort of arrow or other marker indicating that we can scroll. For the headers, we could keep them frozen as the user scrolls down. There's an interesting scenario where, when scrolling horizontally, it would make sense for the first column of headers to remain frozen while the others scroll beneath it.

To close this issue, we should pick a strategy. We can separate implementation into other issues.

**Comment by jehlers** [comment]
We should also probably keep the print.css in mind for these tables. The overflow is hidden when attempting to print right now.

**Comment by cmc333333** [comment]
Great catch @jehlers

**Comment by Journerdism** [comment]
Closing, documentation and going forward should focus on #125: https://github.com/18F/atf-eregs/issues/125
