### ISSUE TITLE
27 CFR 555 2014-18842 Customs Officer

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#122]
https://www.federalregister.gov/articles/2014/08/11/2014-18842/technical-amendments-to-regulations#h-26 indicates that the definition of "Customs Officer" changed, but the data seems to indicate that this was the definition before.

Confirm that our data is okay, then check with ATF what's up

**Comment by tadhg-ohiggins** [comment]
The definition of Customs Officer is the same in 555 going back to 2010, at least according to the GPO version (<http://www.gpo.gov/fdsys/pkg/CFR-2010-title27-vol3/xml/CFR-2010-title27-vol3-chapII-subchapC.xml>), so it looks as if this is a mistake in the 2014-18842 notice, and we should point it out to ATF at our next meeting. I'll close this issue once we tell them about it.

**Comment by cmc333333** [comment]
I'm betting https://www.federalregister.gov/articles/2015/10/02/2015-25190/technical-amendments-to-regulations-correction#p-amd-2 has something to do with this

**Comment by tadhg-ohiggins** [comment]
Agreed, the ATF appears to know about this, closing.
