### ISSUE TITLE
Beta warning

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#138]
FEC's looks like:
<img width="1226" alt="screen shot 2015-12-01 at 11 08 01 am" src="https://cloud.githubusercontent.com/assets/326918/11506116/bd807246-981b-11e5-8746-882991063096.png">

We skipped this the last time around due to limited resources, but we should revisit

**Comment by jehlers** [comment]
@cmc333333 Is the goal here to have a beta label or a "This is an official website of the US Gov" banner?

ATF has the latter at the bottom of their website:

<img width="1279" alt="screen shot 2015-12-01 at 5 24 23 pm" src="https://cloud.githubusercontent.com/assets/4267825/11516281/6c3ce858-9850-11e5-9974-e2223aa7db20.png">

**Comment by cmc333333** [comment]
@jehlers the "beta" bit is the important piece. We should follow up with ATF whether they need the "official website" stuff

**Comment by jehlers** [comment]
:+1:

**Comment by jehlers** [comment]
Ok! Here are a few options that I tried for the beta warning. 

#### Option 1 - The best one

I think subtly is best when it comes to beta labels. This option puts the label right next to the eRegulations "logo-ish" text. It allows us to easily keep the word on every page, and doesn't call too much attention to itself or disrupt the normal legibility of that top header. 

![atf-betalabel-01a](https://cloud.githubusercontent.com/assets/4267825/11545168/c5a5f9d4-9913-11e5-9e76-3a2abf4970b0.png)

#### Option 2 - Following FEC's Lead

I think FEC does a great job at using plain language in this top bar, and linking back to the normal fec.gov. They, however, have the benefit of less forms of navigation so close to this bar. Most of the options I tried for this design made the top area feel extra "strip-y." If we end up needing the  "This is an official gov site" type text, this would be a good option. 

![atf-betalabel-01b](https://cloud.githubusercontent.com/assets/4267825/11545275/7802961e-9914-11e5-9f4b-e2dec57db2a8.png)

#### Option 3 - Using our empty space

This last option uses the empty space on the right of the wayfinding bar. I think this is just as subtle as the first option, but I'm not sure where it would live on mobile. If we think this is worth exploring, I can do that, but I figured for now I would put it here as an option.

![atf-betalabel-01c](https://cloud.githubusercontent.com/assets/4267825/11545440/57f81686-9915-11e5-8ce2-5e480c4032f9.png)

**Comment by cmc333333** [comment]
I'm relatively against putting another bar at the top of the site just to say "beta" (i.e. mockup 2). If we'll go with that approach we should probably also put on the "this is an official government website" text to make use of the space

**Comment by jehlers** [comment]
@cmc333333 I agree, I feel that the first option is the strongest, and the easiest to take away once the site is no longer in beta. But, how do you feel about this if we do bring in that text?

![atf-betalabel-01d](https://cloud.githubusercontent.com/assets/4267825/11721428/bfbf60c2-9f31-11e5-9855-a49c92927977.png)

And here is what it would look like on mobile either way (it also follows the FEC (https://beta.fec.gov/) interaction, which is strong.

![atf-betalabel-01b-mobile](https://cloud.githubusercontent.com/assets/4267825/11721475/f7219184-9f31-11e5-898a-e5f4c5bab2f0.png)

We may want to keep the above interaction even if we go with option 1.

**Comment by jehlers** [comment]
We could also put the message in the global menu for either option:

![atf-betalabel-01c-mobile](https://cloud.githubusercontent.com/assets/4267825/11721741/5b410928-9f33-11e5-92f6-cdb262975792.png)

**Comment by jehlers** [comment]
**Another option would be to not have a beta label at all.**

Beta labels usually imply that the system functionality is not complete or working correctly. In this case, I think we are more worried about the content than the tool functionality, and we do have the warnings at the beginning of each regulation to explain this to our users (#137). Those could be all we need? Thoughts?

**Comment by Journerdism** [comment]
Andrew and Hadiza said they prefer option #1!
