### ISSUE TITLE
Supplement I reference in the Help module

### ISSUE THREAD

**Issue by jehlers** [18F/atf-eregs#139]
![screen shot 2015-12-01 at 12 12 56 pm](https://cloud.githubusercontent.com/assets/4267825/11509202/c784b9e6-982a-11e5-9e1f-c2f7c98f7d03.png)

We should probably take this out since all other references to these explandables have been taken out.

**Comment by cmc333333** [comment]
Ideally, we'd add a setting for "include interpretations" and just set that to `False` rather than overriding a template. This would move us towards the concept of a product line.

**Comment by jehlers** [comment]
Similarly, should this (example 1005.8(b)) text stay or change to match an actual example per agency?

![screen shot 2015-12-02 at 11 44 22 am](https://cloud.githubusercontent.com/assets/4267825/11537259/3ce4bee2-98ea-11e5-8c11-10fd0125c548.png)

**Comment by cmc333333** [comment]
This'd be a little easier with 18f/regulations-site#59. It'd allow us to pass the settings through to the template and only display the interpretations bit if we were configured to include it.

**Comment by cmc333333** [comment]
Marking this as blocked due to that PR, though I'll prep a PR assuming 59 isn't too far from the mark
