### ISSUE TITLE
Global menu link color on mobile

### ISSUE THREAD

**Issue by jehlers** [18F/atf-eregs#146]
To match ATF styles, we should either update the background color on mobile to match that of the desktop size, or change the link color so they are legible against the gray drop down.

![screen shot 2015-12-02 at 11 01 08 am](https://cloud.githubusercontent.com/assets/4267825/11535950/3383e7a2-98e4-11e5-895e-362df8ded2eb.png)

**Comment by cmc333333** [comment]
@jehlers what do you think of this? Last entry is highlighted
<img width="803" alt="screen shot 2015-12-07 at 3 20 24 pm" src="https://cloud.githubusercontent.com/assets/326918/11638639/0bc51676-9cf6-11e5-9050-5506830974d0.png">

The same, on CFPB's instance
<img width="772" alt="screen shot 2015-12-07 at 3 20 48 pm" src="https://cloud.githubusercontent.com/assets/326918/11638633/07901e3e-9cf6-11e5-995b-a9f30a2536ca.png">

**Comment by jehlers** [comment]
@cmc333333 is the last entry a hover or click color? I think the only reason the last entry is darker for CFPB is because the blue on the light gray is not 508 compliant (that's my guess). Can we make all of the menu that medium blue so that it matches the on state for the menu icon? Similar to the gray in the CFPB version.

**Comment by cmc333333** [comment]
After a quick chat, the strategy will be to make the background for the menu options that lighter shade of blue and have the :hover state be the darker shade (effectively flipping the colors from the above screenshot)
