### ISSUE TITLE
Sliding nav caret is pointing the wrong direction

### ISSUE THREAD

**Issue by jehlers** [18F/atf-eregs#147]
This is still very functional, but the caret that opens and closes the left sliding nav should be pointing the opposite way of where the nav is. This way users know where the nav will go when they click on the caret. Right now, the caret is pointing the same direction as the nav's current position: 

![04409e45170d34970b20dcac0bd41580](https://cloud.githubusercontent.com/assets/4267825/11536452/8f96ecb8-98e6-11e5-80d4-0f09f31f2371.gif)

So it just needs to be flipped: :smile: 

![screen shot 2015-12-02 at 11 17 45 am](https://cloud.githubusercontent.com/assets/4267825/11536582/0a624d5c-98e7-11e5-9afc-5f49245af83c.png)

This is something that is currently on the CFPB version of the platform as well, so we should update both versions whenever we fix this. 

cc @ascott1

**Comment by cmc333333** [comment]
Resolved by 18f/regulations-site#51
PR sent to CFPB: cfpb/regulations-site#761
