### ISSUE TITLE
Parse TTITLE into CAPTION

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/atf-eregs#156]
Currently we take TTITLE elements within GPOTABLEs and turn them into a full-width table header row. We should be turning them into HTML caption elements, as this fits what they are semantically.

This involves linked changes to -parser and -site.

**Comment by cmc333333** [comment]
@tadhg-ohiggins everything's merged. Good to close?

**Comment by tadhg-ohiggins** [comment]
I've been waiting until I see that issues are fixed on the demo site; I'll close it when that happens.

**Comment by cmc333333** [comment]
Data's updated on demo and the titles look good to me. Please close this issue if you confirm
