### ISSUE TITLE
Customs Officer ambiguity in 2014-18842

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/atf-eregs#158]
Why does this not change all instances, like every other change in that rule, and instead call out specific ones?
https://www.federalregister.gov/articles/2014/08/11/2014-18842/technical-amendments-to-regulations#p-amd-60

It's quite possible that it does exactly what it's supposed to, and rather than changing a title it's assigning some responsibilities to another official, but we should ask.

**Comment by cmc333333** [comment]
@tadhg-ohiggins I think we just need to send an email over to ATF, yes?

**Comment by tadhg-ohiggins** [comment]
I was finishing off this email when I realized the answer is clear from the text: the new title came into effect after 2003-05-24, so the section referring to licensure prior to that date refers to the old title, and the later section to the new title. Closing.
