### ISSUE TITLE
27 CFR 447 Version Verification

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#163]
* [x] 03-1657 2003 Annual
* [x] E7-24910 2008 Annual
* [x] E8-23178 2009 Annual
* [x] 2013-09392 2014 Annual
* [x] 2014-02580 Final Rule
* [x] 2014-06778 Final Rule
* [x] 2014-18842 2015 Annual
* [x] 2015-12992 Final Rule

**Comment by cmc333333** [comment]
No expectation that this will be completely done this sprint, but adding to the milestone anyway. Break it up as needed

**Comment by tadhg-ohiggins** [comment]
Findings on the current state of 447:

The notes in /447-21/E7-24910 look odd, and also seem to become notes between 2003 and 2007, when it seems like they probably should have been notes all along (likely a problem with the source XML).

/447-21/E7-24910 looks as though it has had rather more changes than https://www.federalregister.gov/articles/2007/12/26/E7-24910/us-munitions-import-list-and-import-restrictions-applicable-to-certain-countries-2005r-5p#h-19 would suggest.

/447-43/2013-09392 is missing the change from https://www.federalregister.gov/articles/2012/02/06/2012-2472/importation-of-arms-ammunition-and-implements-of-war-and-machine-guns-destructive-devices-and

/447-43/2014-02580 is missing the change from https://www.federalregister.gov/articles/2014/02/07/2014-02580/importation-of-arms-ammunition-and-implements-of-war-and-machine-guns-destructive-devices-and (which seems to be the same as the change from 2012-2472…).

/447-21/2014-06778 seems to be missing all of the changes from https://www.federalregister.gov/articles/2014/03/27/2014-06778/importation-of-arms-ammunition-and-defense-articles-removal-of-certain-defense-articles-currently-on

/447-43/2014-18842 has the change from "one year" to "two years" first mentioned in https://www.federalregister.gov/articles/2012/02/06/2012-2472/importation-of-arms-ammunition-and-implements-of-war-and-machine-guns-destructive-devices-and

**Comment by tadhg-ohiggins** [comment]
In addition, do we want to make URLs links generally? atf.gov is in there a few times and it seems strange to see it not being clickable.

**Comment by cmc333333** [comment]
URL links seems like a great idea (hello again, formatting layer discussion). Probably not essential for this issue, though

**Comment by cmc333333** [comment]
### E7-24910
* 18f/regulations-parser#145 removes some superfluous diffs
* #187 has been created as diffs of notes aren't _displaying_ properly

### 2013-09392
* No need to include the change in `2012-2472`, as that's a _proposed_ rule
* #205 describes an odd problem with diff displays
* #187 is also problematic here
* #206 describes an issue where re-ordering "categories" causes significant issues in the diff view

### 2014-02580
* 18f/fr-notices#14

### 2014-06778
Needs lots of manual edits. I'm thinking that #206 will make these edits easier, however

### All versions
* #204 requests we remove the ability to make new definitions in notes
* #185 describes how the munitions list looks rather janky

**Comment by cmc333333** [comment]
Ended up with 18f/fr-notices#15 to account for 2014-06778. As the regulation trees are okay, and all of the issues with diffs have been created, I'm going to mark this issue done.
