### ISSUE TITLE
Create new theme layer repo in eregs repository

### ISSUE THREAD

**Issue by jbarnicle** [18F/atf-eregs#164]
Pull out the existing css (less) / javascript into a new repo.  Methodology for importing that into the various -site repositories to follow.

**Comment by jehlers** [comment]
:smiley: @jbarnicle would it make sense to combine the general brand issue ( #133 ) as the first implementation of this new theme layer?

**Comment by jbarnicle** [comment]
@jehlers - indeed - I think that would be a good implementation test.

**Comment by cmc333333** [comment]
John, Jen & Theresa discussing Monday
#188
