### ISSUE TITLE
Static Table Header Bugs

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#172]
Add bugs as comments w/ checkboxes, pretty please

**Comment by cmc333333** [comment]
* [ ] Doesn't show the full header
<img width="598" alt="screen shot 2015-12-10 at 4 32 31 pm" src="https://cloud.githubusercontent.com/assets/326918/11729098/81686178-9f5b-11e5-997a-d1db399136cc.png">
<img width="601" alt="screen shot 2015-12-10 at 4 32 20 pm" src="https://cloud.githubusercontent.com/assets/326918/11729099/816a7454-9f5b-11e5-8de5-bbdddf6247a1.png">
* [ ] Doesn't pay attention to padding
<img width="734" alt="screen shot 2015-12-10 at 4 33 47 pm" src="https://cloud.githubusercontent.com/assets/326918/11729149/bc10446c-9f5b-11e5-9bf1-72d019e4a08f.png">
* [ ] Horizontal scrolling doesn't stay synced with the header
<img width="669" alt="screen shot 2015-12-10 at 4 35 05 pm" src="https://cloud.githubusercontent.com/assets/326918/11729166/d6f17a80-9f5b-11e5-8bc8-3d241c3db80d.png">
* [ ] Doesn't redraw when the TOC is opened or closed
<img width="928" alt="screen shot 2015-12-10 at 4 35 34 pm" src="https://cloud.githubusercontent.com/assets/326918/11729188/f12b58da-9f5b-11e5-9b4f-083ddfe9c190.png">

**Comment by cmc333333** [comment]
After switching to datatables, bugs that I see are are
* Horizontal scroll bar can't be clicked
* Columns don't quite line up
<img width="557" alt="screen shot 2015-12-16 at 4 41 48 pm" src="https://cloud.githubusercontent.com/assets/326918/11854712/c2e8fba0-a413-11e5-8611-bf9cfa6f8f0d.png">
* Can't scroll horizontally when focused on the table header

**Comment by jbarnicle** [comment]
@cmc333333 - I broke this out into issues #219, #220, and #221.  If it looks like those three bugs cover the remaining issues, you can close this one.

**Comment by Journerdism** [comment]
Closed for 3 remaining bugs!
