### ISSUE TITLE
TOC is still visible when left drawer is closed

### ISSUE THREAD

**Issue by jehlers** [18F/atf-eregs#189]
When the left drawer is closed you can still see and use the Table of Contents sections. This shouldn't happen. 

<img width="69" alt="screen shot 2015-12-18 at 12 04 37 pm" src="https://cloud.githubusercontent.com/assets/4267825/11905639/8e367210-a595-11e5-8190-038d4225167b.png">

Here's what it looks like in the CFPB version:

<img width="56" alt="screen shot 2015-12-18 at 2 45 02 pm" src="https://cloud.githubusercontent.com/assets/4267825/11905725/f59940c2-a595-11e5-9d8b-3425442c5c1c.png">

**Comment by jbarnicle** [comment]
@jehlers I'm not completely sure I understand what the issue is here.  Can you maybe elaborate a little bit?

**Comment by jehlers** [comment]
@jbarnicle Sorry, I could have been clearer. 

See how in the ATF version there are lines and the light blue "you are here" color sticking out when the drawer is closed? Since the user can't actually see the sections they pertain to when the drawer is closed, they shouldn't see those or be able to use them when the drawer is closed (like the cleaner CFPB version). Does that make sense?

**Comment by jbarnicle** [comment]
@jehlers Actually I'm not seeing it in my browser.  Do you mind including what browser and site (demo / prod) you're seeing this in?

**Comment by jehlers** [comment]
@jbarnicle I'm in Chrome, and I see it on production and demo. I also see it in Safari and Firefox.

**Comment by cmc333333** [comment]
Not sure when this was fixes, but it appears to have been.
