### ISSUE TITLE
Update ATF logo

### ISSUE THREAD

**Issue by jehlers** [18F/atf-eregs#192]
To match the website branding, let's use the image of the ATF logo instead of small text.

<img width="1023" alt="screen shot 2015-12-22 at 10 34 07 am" src="https://cloud.githubusercontent.com/assets/4267825/11958742/9ea28044-a897-11e5-8654-236720af464f.png">

**Comment by jbarnicle** [comment]
@jehlers - is the logo available somewhere?  @theresaanna - I was gonna grab this one unless you've already started.

**Comment by jbarnicle** [comment]
Ooops - never mind.  I will just grab the assets from the ATF.gov site

**Comment by jehlers** [comment]
Yeah, I have a high res seal if we think that will help. But I took the ATF letters straight from the website.

**Comment by jehlers** [comment]
@jbarnicle :tada: logos! Is it possible to control the sizing and spacing a little bit more? 

The seal is currently equidistant from "About" and "ATF" when it should be more closely connected to "ATF" since "the seal + the ATF" text is the logo.

And, is it possible to shrink them a little bit so that there is more space above and below them?

**Comment by cmc333333** [comment]
Reopening per @jehlers requests

**Comment by jbarnicle** [comment]
@jehlers Of course.  Right now there is a .25 em margin to the right of the seal - I will remove that.  If we need them to be closer after that, we'll need to edit the image.  The seal is currently 45px tall / the text is 100px tall with some spacing in the image.  Make the seal 40px and shrink the text by the same percentage?

**Comment by cmc333333** [comment]
I believe this is complete now and pushed to demo. Please reopen if there are more issues.
