### ISSUE TITLE
Get high level documentation into RTD

### ISSUE THREAD

**Issue by theresaanna** [18F/atf-eregs#194]
- Look into how to get custom pages or what have you into Read the Docs
- Will we have three different instances - for -site, -core, -parser?
    - Where should different RTD instances be united? 
- Think about a starting organization for the content

Related: https://github.com/18F/atf-eregs/issues/64

**Comment by cmc333333** [comment]
We've made some pretty big leaps and bounds here:
* https://eregs.github.io/
* https://eregs-parser.readthedocs.org/
* https://regulations-site.readthedocs.org/
* https://atf-eregs.readthedocs.org/

I'm going to close this as an ongoing task.
