### ISSUE TITLE
Write reg primer + glossary type docs

### ISSUE THREAD

**Issue by theresaanna** [18F/atf-eregs#195]
Sprint D goal: to get a draft of general information about regulations, the structure of a regulation and some related terms written. Hoping @jehlers will help with feedback and suggestions once there's a draft.

**Comment by jehlers** [comment]
@theresaanna is there a draft somewhere I can help with now that I'm back?

**Comment by theresaanna** [comment]
https://docs.google.com/document/d/1x4PPCVgogRYl-RXUdJg1O5bVbiXnpEgXVgI7ul9Eij8/edit in progress

**Comment by brittag** [comment]
Working on this in a fork of the main eRegs documentation repository! [Here's what I have so far.](https://github.com/brittag/eRegulations/blob/intro/_pages/introduction.md)

**Comment by cmc333333** [comment]
@brittag nice work! Quick note to give context: the terms we've defined in that doc are how the terms are used _within eRegs_. Many have more specific usage outside of our tool.

**Comment by jehlers** [comment]
+ :100: 

One note, I'm not sure how important this is, but:
> After the agency receives feedback, the agency must address each unique comment and draft a “final” rule which incorporates this feedback. 

That is right IF an agency writes a final rule, but I don't think they _have_ to write a final rule. They could just not follow up with the proposed rule or try again with a different proposed rule. Again this may be nitpicking too much, but I wanted to bring it up just in case.

**Comment by cmc333333** [comment]
Good point @jehlers . Agencies can drop the proposal entirely, though I wonder if they publish a notice saying as much.

**Comment by jehlers** [comment]
@brittag For this one:

> Interpretation: This is a component of a regulation which appears to be specific to CFPB (and perhaps other financial regulators). These regulations include a final appendix (“Supplement I”) which provides further analysis, explanation, and examples of the regulation and its appendices. We’ve displayed these in-line with the text they are describing.

"Official interpretations" in Supplement I are specific to CFPB and maybe other financial regs, but the word "interpretation" could apply to a lot of docs like ATF's rulings or FEC's advisory opinions.

**Comment by jehlers** [comment]
Ok, last comment: 

> Version: ~~This is a term that lawyers will not use, but which makes discussing eRegulations much easier.~~ As we track how the regulation changes over time, we generate different versions of it. These versions are given unique identifiers (usually corresponding to the document number of the final rule which caused the change) and associated with specific effective dates. 

I think this works well without the first sentence. Should we also talk about the "table of contents" and "Regulations timeline"? Those are two features within eregs... so maybe not, but "Version" made me think of them.

**Comment by brittag** [comment]
Thanks for these comments - definitely helpful! I've clarified those bits and added some more context and links, and I've put the result into a pull request: https://github.com/eregs/eRegulations/pull/15

It looks like the "table of contents" and "regulations timeline" features already have nice illustrated descriptions in the [standard user-facing "about" page for eRegulations](https://atf-eregs.apps.cloud.gov/about) (which seems like the right place for that), so I'm thinking we don't need to define them a second time in this glossary. I could link to one of those "about" pages from this background page to explain more about eRegulations features - the slightly tricky part is figuring out whether to link to the [CFPB version](http://www.consumerfinance.gov/eregulations/about) or the [ATF version](https://atf-eregs.apps.cloud.gov/about) (or both).

**Comment by jehlers** [comment]
Oh right! Sorry, completely forgot about that page for a minute.

**Comment by brittag** [comment]
Filed a suggestion at https://github.com/eregs/eRegulations/pull/17 to make sure the "about" pages are visible from the main docs. :)

**Comment by brittag** [comment]
This primer is now living at http://eregs.github.io/eRegulations/introduction/ - so I'll close this!
