### ISSUE TITLE
Set up a long-term logging service

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#196]
Right now, we log to stdout. While cloud.gov gives us access to those logs for a while, it'd be good to integrate a longer term service. Diego notes that cloud.gov has an ELK service.

**Comment by jmcarp** [comment]
Logs are now stored for 180 days on cloud.gov: see https://docs.cloud.gov/apps/logs/#historic-logs:6d6e87c8985e9c9e781f22ee066f5a45. Logs are available at https://logs.cloud.gov/app/kibana. Is this adequate?

**Comment by cmc333333** [comment]
:+1:
