### ISSUE TITLE
Spin up multiple instances

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#199]
Right now we use only a single instance, yet are paying for a quota. Spin up more instances for production.

This requires modifying the startup script so that only one instance clears the search index, migrates the DB, etc.

**Comment by cmc333333** [comment]
Note that we _do_ have multiple instances now, but _each_ clears the search index, etc. on boot.

**Comment by jmcarp** [comment]
Can this be closed now that we've merged #325?

**Comment by cmc333333** [comment]
Yessir
