### ISSUE TITLE
Rethink deploying data and assets

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#201]
Related to #107 

Diego's suggested using CI to build and deploy both data and assets automatically. Does this make sense? It would resolve some risks for human error. Investigate and create a plan forward.

**Comment by jmcarp** [comment]
I'd be down to at least get assets building on CI--iirc, @cmc333333 mentioned an interest in setting this up for dev only to start with.

**Comment by cmc333333** [comment]
Sounds good @jmcarp . If you want to start thinking of prod, too, maybe we tie everything to the creation of a github release?
