### ISSUE TITLE
Can't select text before an extract

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#210]
https://atf-eregs.apps.cloud.gov/478-103/2014-18392#478-103-e

Can't use the cursor to select the text in paragraph (e). I'm betting this is due to a `div` inside the `p`s. This may also be the cause of being unable to scroll horizontally via the scroll bar on large tables

**Comment by cmc333333** [comment]
From @jehlers 
> this is my issue i can select (e) by the E and the "The" but any futher in, it selects the (1) below.

![e5e556253b14806600b8a3720a515a97](https://cloud.githubusercontent.com/assets/326918/12053891/14d8e608-aee3-11e5-925d-13f918748e0b.gif)

**Comment by cmc333333** [comment]
This was fixed in 18F/regulations-site#64

**Comment by jehlers** [comment]
I still see this issue in the link above in Chrome.

**Comment by cmc333333** [comment]
@jehlers on the demo site?

**Comment by jehlers** [comment]
You're right sorry! It's all good here :) !
