### ISSUE TITLE
Super bold text in Safari

### ISSUE THREAD

**Issue by jehlers** [18F/atf-eregs#211]
In Safari I'm seeing a lot of extra bold text, I'm not sure why. The fonts look normal in Chrome and Firefox.

![screen shot 2015-12-30 at 1 57 37 pm](https://cloud.githubusercontent.com/assets/4267825/12055684/7b4b23aa-aefd-11e5-93a9-97d70fdcd93a.png)

**Comment by cmc333333** [comment]
I wonder if this is due to the automated bolding the browser's performing (rather than having a weighted font)

**Comment by jehlers** [comment]
@cmc333333 that's very likely! We can definitely hold off on this until the new type hierarchy is implemented. If this isn't fixed at that point, we can try to fix it then. :)

**Comment by jbarnicle** [comment]
So it seems that this is just how Safari displays that font at a weight of 800.  From what I can tell the style is being applied the same across all browsers.  It appears quite bold in Firefox as well.

**Comment by jbarnicle** [comment]
@jehlers - I think this went away with the new fonts,  It looks ok to my design-challenged eyes.

**Comment by jehlers** [comment]
Yep! :tada:
