### ISSUE TITLE
Implement Jen's hierarchy and document related CSS

### ISSUE THREAD

**Issue by theresaanna** [18F/atf-eregs#214]
- rename/refactor CSS to support more generic naming and consistency around colors and fonts
- implement these styles https://github.com/18F/atf-eregs/issues/191
- remove old ATF style overrides

**Comment by jehlers** [comment]
We should also think about how the type sizes bump down for mobile. I usually expect the H levels to essentially bump down in size, so when we are on a smaller screen H1 becomes H2 size, and H2 size becomes H3. Once we get down to the body size (so H5 and H6) they can stay that size. We don't want to go much smaller than that, or bump our smaller sizes down even further. Thoughts @theresaanna and @jbarnicle ?

**Comment by jbarnicle** [comment]
Design wise I think it's your call.  Definitely a good think to keep in mind as we implement tho.

**Comment by jbarnicle** [comment]
@jehlers Will the remaining elements - navigation, etc - use the same font styles that they are using today (Work Sans, etc)?

**Comment by jehlers** [comment]
@jbarnicle no we should not use work sans at all in favor of the new fonts. I tried to define everything in the doc with these things:

<img width="207" alt="screen shot 2016-01-27 at 10 04 10 am" src="https://cloud.githubusercontent.com/assets/4267825/12617386/76274d86-c4dd-11e5-94f9-5b9aa033d06f.png">

<img width="775" alt="screen shot 2016-01-27 at 10 04 25 am" src="https://cloud.githubusercontent.com/assets/4267825/12617392/7a845d88-c4dd-11e5-853f-2cd233ad2f55.png">

I can send you the full doc if need be. :smiley:
