### ISSUE TITLE
ATF-specific parsing

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#217]
To implement the US Code snippets, rulings, etc. we'll need code and configurations for the _parser_ specific to ATF. On the UI side, we implement this by wrapping `regulations-site` as a library and importing it. Does that make sense here?

Alternatives include the original solution, `regcontent`, which was a library you'd reference in your parsing config. This has been largely replaced with [`regconfig`](https://github.com/cfpb/regulations-configs), i.e. a library that can be loaded which will be auto-discovered by the parser. I think this is probably the way to go, but let's do some research into building a straight forward solution. Research Python-Markdown and other libraries within plugins to see how they implement plugins.

To close this issue, let's have a working plugin system for the parser.

**Comment by cmc333333** [comment]
We can roll our own via setup files: http://docs.pylonsproject.org/projects/pylons-webframework/en/latest/advanced_pylons/entry_points_and_plugins.html

Or use an existing [library](https://github.com/openstack/stevedore) which wraps that a bit

**Comment by cmc333333** [comment]
I kind of glossed over the `regcontent` and `regconfig` stuff -- basically, we used to assume that all of these agency-specific things would live in configuration files more than anything else. We're now expecting some custom functionality (e.g. being able to parse ATF Rulings) in addition to custom configuration (e.g. knowing that "ATF I 5300.1" refers to a specific pdf)

**Comment by tadhg-ohiggins** [comment]
I think the extension system covers this. Closing.
