### ISSUE TITLE
New footer on the homepage

### ISSUE THREAD

**Issue by jehlers** [18F/atf-eregs#218]
Hadiza has approved this footer on the universal homepage.

![44423fda-a898-11e5-96ae-6c2118038c23](https://cloud.githubusercontent.com/assets/4267825/12096985/03dc99be-b2e7-11e5-942c-a06c5da1c9e9.png)

**Comment by jbarnicle** [comment]
@jehlers Is there a design document that I can get info like font family / size / weight and footer height?  Also - so you know offhand if that icon to the far right is in the Capital Framework Icons font (cf-icons) - or should I be pulling it from somewhere else?

**Comment by jehlers** [comment]
@jbarnicle Sorry I should have documented that for you before. 

- The external link icon is part of the cf-icons. We also use it in other places like the drop down menu on mobile.
- The font is white, Lato Semibold, 16px (body size). 
- 30px of visual space above and below the text should get you the height. In my file the dark blue bar is about 72px tall.

**Comment by cmc333333** [comment]
Quick note re external links: just add `class="external" target="_blank"` and the icon will be automatically added. See https://atf-eregs.apps.cloud.gov/about for examples

**Comment by jbarnicle** [comment]
Thanks @cmc333333 - that will save me a bit of time.

**Comment by cmc333333** [comment]
I believe this is complete and pushed to demo. Please reopen if there's more
