### ISSUE TITLE
US Code Copy to Clipboard

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#225]
![img](https://cloud.githubusercontent.com/assets/4267825/12066532/3889bf9e-afb7-11e5-8334-2ef3c849aee2.png)

**Comment by jbarnicle** [comment]
So the text in the actual document will include a lot of markup - and potentially external links, etc.  Would the idea to copy it in that raw form, or would be try to first sanitize into a plain text format?

**Comment by cmc333333** [comment]
Excellent question. We certainly don't want to copy the raw HTML; let's start with plain text. In a quick test using jQuery's `.text()`, it looks like we may run into some problems with
1. Excessive newlines
2. Hidden elements appearing in the output
Otherwise, it didn't look too bad.

**Comment by jbarnicle** [comment]
I was also thinking that if we could implement this as an service call to move that processing to the server.  Not sure if that would make sense here.

**Comment by cmc333333** [comment]
I can imagine a plain text only endpoint would be useful. That increases the scope of this ticket quite a bit, though. Let's prototype with `.text()` or similar for now and circle back once we have more feedback that we're on the right track?

**Comment by jbarnicle** [comment]
Yep.
