### ISSUE TITLE
Extra spacing beneath header in Firefox

### ISSUE THREAD

**Issue by jbarnicle** [18F/atf-eregs#240]
![screen shot 2016-01-12 at 10 24 54 am](https://cloud.githubusercontent.com/assets/737400/12269440/03f03d4e-b917-11e5-9e47-5be11ad78ac7.png)

**Comment by cmc333333** [comment]
Huh. what version of FF?

<img width="807" alt="screen shot 2016-01-13 at 2 46 30 pm" src="https://cloud.githubusercontent.com/assets/326918/12305802/835e4236-ba04-11e5-9e52-6b5ccaec4cae.png">

**Comment by jbarnicle** [comment]
43.0.4 - Mac OSX Yosemite

**Comment by jbarnicle** [comment]
I'll try disabling a few plugins to see if that might be somehow causing the extra space

**Comment by jbarnicle** [comment]
Removing the explicit height of 3.75em fixes the issue in my FF.

**Comment by jbarnicle** [comment]
This was fixed in #248 by removing the fixed height from the header
