### ISSUE TITLE
447.32 table is rendering strangely 

### ISSUE THREAD

**Issue by jehlers** [18F/atf-eregs#250]
![screen shot 2016-01-14 at 10 13 25 am](https://cloud.githubusercontent.com/assets/4267825/12328298/cf0c3b4e-baa8-11e5-9375-9cce34a5f340.png)

Two issues:

1. the wayfinding doesn't seem to be following my scroll and updating with the paragraph level.
2. the table is cut off?

sort of 3 - @cmc333333 said: looks like JS broke: `Cannot read property 'mData' of undefined`

**Comment by cmc333333** [comment]
@jbarnicle 's fix (18f/regulations-site#74) appears to work on demo. Please reopen if something's been missed.
