### ISSUE TITLE
Remove `RegsHelpers.idToRef` from JS

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#259]
Instead, include these in the markup; this removes redundancy between the backend and frontend.

**Comment by xtine** [comment]
I am looking in the files that contain `RegsHelpers.idToRef` and they mainly point to a defined function named `changeTitle` that populates subhead with a new title. However, I can't seem to find where the function is used and what pages it affects. Help?

**Comment by cmc333333** [comment]
Resolved in eregs/regulations-site#309
