### ISSUE TITLE
Hybrid landing page with buttons and lots of text links

### ISSUE THREAD

**Issue by Journerdism** [18F/atf-eregs#263]
Jen working with Britta mock up a hybrid CFPB button and text version of the landing page

**Comment by jehlers** [comment]
Using @brittag's awesome text:

<img width="512" alt="screen_shot_2016-01-15_at_10 06 05_am_1024" src="https://cloud.githubusercontent.com/assets/4267825/12361220/d80d63ca-bb8a-11e5-9f04-574dc1fa6633.png">

Thinking about this page as the intersection between power users, or lawyers who are used to reading regulation text, and new users seeing this reg for the first time. This is the initial inspiration or attempt at this at CFPB, but never went live:

![screen_shot_2016-01-15_at_10 18 23_am](https://cloud.githubusercontent.com/assets/4267825/12361246/051992d0-bb8b-11e5-9b84-7c98b8ba57ca.png)

**Comment by jehlers** [comment]
Alright, after some discussion we've come up with a direction that brings the two above ideas together.

#### 478 Landing page

This page is meant to provide easy links into sections of the regulation. To keep with our normal internal link style, the top section "Important topics include:" is still a bulleted list. But we do have ways of sectioning these off if needed to help with reading and grouping.

We've also added a search box onto this page. It helps to invite users to search for things if they don't know where to go in the regulation first. We've also provided some search "tags" to help facilitate this search. If a user clicks on one of these tags, they will be taken to a search results page. Same as if they clicked search in the search box.

We've also sectioned off the legal disclaimer to show that it is not just for this reg, but the whole tool.

![maybefinal478](https://cloud.githubusercontent.com/assets/4267825/12630338/fb4663b2-c519-11e5-831b-6efd131b45c0.png)

#### 447 Landing page

Here's another example of how this pattern could work. 

![maybefinal447](https://cloud.githubusercontent.com/assets/4267825/12630446/70df5052-c51a-11e5-8847-ab6c1349561b.png)

#### Images

One thing I tried was bringing images into this page. It is very text and blue heavy as is. I think it does a good job of helping someone digest the content as they scroll, but it's always nice to try something else.

![screen_shot_2016-01-27_at_3 41 02_pm](https://cloud.githubusercontent.com/assets/4267825/12630497/c163f212-c51a-11e5-99ea-f7ad055eba8f.png)

I don't think the page _needs_ this, but it works if we like extending the tear drop motif from ATF.gov. The only issue is finding photos for each reg title. 

#### Mobile

Also, I just want to show that this layout does work on mobile. The right sidebar should fall in line below the search but above the legal disclaimer if possible. And if we go with the above tear drop image, I would hide it on mobile for load performance and space purposes. 

![b](https://cloud.githubusercontent.com/assets/4267825/12630564/0db5cef6-c51b-11e5-8dea-7028b173e988.png)

Thoughts?

**Comment by jehlers** [comment]
These layouts are go! Should make a new issue to implement them @Journerdism?

Also I will work with Hadiza to figure out how to get stock images for all the reg's tear drop images.

**Comment by Journerdism** [comment]
Sure, that sounds good
