### ISSUE TITLE
Learnings and initial sketches from the past few weeks of research

### ISSUE THREAD

**Issue by jehlers** [18F/atf-eregs#266]
As we start to synthesize the research about rulings and other ATF documents that we want to link to, this is an issue where we can collect some of those thoughts and learnings for discussion.

**Comment by brittag** [comment]
Here's a sketch of what a regulation landing page could look like, to help readers feel confident that they know where to find all the relevant information for a topic:

![fullsizerender](https://cloud.githubusercontent.com/assets/391313/12564571/cbd74b3e-c364-11e5-85ae-bebcd1b800c5.jpg)

**Comment by jehlers** [comment]
Initial sketches from today's session to follow. 

**On the left:** A user who is starting by looking at a section of the reg can see all related information in the right sidebar. If clicked, the user is taken to a different content reader and sees the full text of the ruling. The table of contents becomes the same as the content that was originally just in the right sidebar so that the user is still in the context of the reg section they were just looking at. They can also click back to go back to that reg section. 

**On the right:** Focusing more on the hobbyist or newbie user to ATF's regulatory content, a new eRegs homepage may be in order. Similar to @brittag's sketch, this new homepage has the regs easily accessible, but also allows for a plain language search and more information like what the most recent rulings are. If a user does a search, then they will be taken to a page where results are tagged by the type of content they are. 

<img width="961" alt="screen shot 2016-01-25 at 4 07 10 pm" src="https://cloud.githubusercontent.com/assets/4267825/12564644/5c0d05b8-c37e-11e5-817c-3649022c9c0a.png">

**Comment by Journerdism** [comment]
![img_1481](https://cloud.githubusercontent.com/assets/406607/12564657/7b84a144-c37e-11e5-8177-54fa78ef91c1.JPG)

**Comment by vrajmohan** [comment]
![vraj_sketch](https://cloud.githubusercontent.com/assets/2066204/12566396/6629f232-c387-11e5-9d66-faca2f096844.JPG)

**Comment by onezerojeremy** [comment]
![img_1661](https://cloud.githubusercontent.com/assets/474916/12566676/e131819c-c388-11e5-8cbc-9acc1f9d5f85.JPG)
![img_1660](https://cloud.githubusercontent.com/assets/474916/12566677/e131a94c-c388-11e5-8d91-31a9cf6bfc2f.JPG)
![img_1659](https://cloud.githubusercontent.com/assets/474916/12566678/e13253a6-c388-11e5-88bc-890655579198.JPG)
![img_1658](https://cloud.githubusercontent.com/assets/474916/12566674/e12f9a8a-c388-11e5-84d3-9c1f4f927036.JPG)
![img_1662](https://cloud.githubusercontent.com/assets/474916/12566675/e1314380-c388-11e5-92e5-b9f9d3f63412.JPG)

**Comment by tadhg-ohiggins** [comment]
The first image is one way the main page could be structured, with regulations to the left, recent Q&As in the center (based on the assumption that they're the most common things users will want to see, an assumption that needs testing), and rulings on the right. Rulings are sorted here in two ways, by date and by “topic”, which assumes that we'll be able to come up with topic areas that apply across our various kinds of content.

![2016-01-25--tadhg--atf-eregs-sketches--main-page](https://cloud.githubusercontent.com/assets/2626258/12570272/f9085e06-c38a-11e5-8533-52263144d0af.jpg)

This is the content page for one of the Q&As, with the primary content in the middle, related regulation content on the left, related ruling content on the right, and related topics on the lower left.

![2016-01-25--tadhg--atf-eregs-sketches--q_and_a-content-page](https://cloud.githubusercontent.com/assets/2626258/12570282/0ae7be8c-c38b-11e5-8146-e8e89a0be456.jpg)

The third image is the content page for a ruling, and has a similar structure to the Q&A content page, with ruling content in the middle, related regulations on the left, related Q&As on the right, and content from relevant ruling excerpts (assuming we can figure out what those might be) on the lower left.

![2016-01-25--tadhg--atf-eregs-sketches--ruling-content-page](https://cloud.githubusercontent.com/assets/2626258/12570287/132dfba6-c38b-11e5-8390-af5f108fc986.jpg)

The last one is a rulings main page, with rulings listed by most recent first, by recency and which regulation they're related to, and by recency and which topic(s) they're related to, again assuming that we can identify topics and also that these are organizational approaches that match how ATF eRegs users look for information.

![2016-01-25--tadhg--atf-eregs-sketches--rulings-main-page](https://cloud.githubusercontent.com/assets/2626258/12570289/1b6ee8fc-c38b-11e5-8ea5-793fbc8da065.jpg)

**Comment by cmc333333** [comment]
![new doc 3_1](https://cloud.githubusercontent.com/assets/326918/12570757/8628cfe2-c3a8-11e5-8caa-5f3adcf73791.jpg)
We may not be able to display the text of all ancillary docs. This embeds a PDF viewer on the left side but includes meta data in the right side. This is very similar to FEC's existing interface.

![new doc 3_2](https://cloud.githubusercontent.com/assets/326918/12570760/89eda044-c3a8-11e5-85c8-216db2d8746c.jpg)
If we do have plain text, we can present some paragraphs. We can find citations and, If arriving from a regulation, we could have definitions. Importantly, we can't keep the original text layout.

![new doc 3_3](https://cloud.githubusercontent.com/assets/326918/12570762/8e054ef2-c3a8-11e5-805a-90c574660e09.jpg)
When reading a regulation, we could have a section in the RHS for related documents. These might be related to a specific subparagraph or a whole section.

![new doc 3_4](https://cloud.githubusercontent.com/assets/326918/12570768/9188f4f2-c3a8-11e5-8588-0a8f7f4bb267.jpg)
Q&As are pretty short compared to rulings. We can put them inline with a slide-down similar to CFPB's interpretations.

![new doc 3_5](https://cloud.githubusercontent.com/assets/326918/12570770/96857520-c3a8-11e5-9865-1a02ccae90e3.jpg)
Entry point for search. Allow selection between "All documents", "Previous versions" (of regulation), and the various types of documents.

![new doc 3_6](https://cloud.githubusercontent.com/assets/326918/12570771/968bea36-c3a8-11e5-8536-593408f24e51.jpg)
Search results are sorted by relevance, but tagged to indicate what type of document. A problem here when mixing these search results is that they aren't always comparable, particularly with different sized documents. For example, "regulations" are documents roughly a paragraph big, yet rulings are multiple pages.

**Comment by jbarnicle** [comment]
![photo 1](https://cloud.githubusercontent.com/assets/737400/12588186/1053f2c2-c41d-11e5-8f4c-5af66e731ae6.JPG)

Simple reg view.  Right rail is utilized to show rulings, related information to the regulation.

**Comment by jehlers** [comment]
#### Rulings 

Seen as blanket variances to the regulation. If you are in compliance with a ruling, it means you are also in compliance with a reg/the law. 

Rulings are written in PDF form and usually signed by the director of ATF. They have a general format: summary, intro, why ATF is making a ruling, and holding. The holding is the most important section.

**Rulings have a list of connection points to the regs and USC at the beginning of each one:**

_from ATF Rul. 2015-1_
<img width="566" alt="screen shot 2016-01-26 at 1 34 43 pm" src="https://cloud.githubusercontent.com/assets/4267825/12590660/117cd97e-c432-11e5-9b7e-bbc2c29b712c.png">

And, **rulings can also connect to other rulings at the bottom of the ruling. They can at least clarify or supersede:**

<img width="304" alt="screen shot 2016-01-26 at 1 35 03 pm" src="https://cloud.githubusercontent.com/assets/4267825/12590703/425fcac4-c432-11e5-8fb4-1aa70d830a41.png">

#### Open Letters

Open letters are written by various branches in ATF. They can be towards a certain group of licensees or to all licensees. 

Open letters are written in PDF from, and there is no standard formatting. 

**They can reference regs, forms, USC, etc.. inside the text of the open letter:**

_from Alaska, Jun 2012, Open Letter, Identification Showing Residence is Neither a Street Address or Rural Route and Box Number_
<img width="708" alt="screen shot 2016-01-26 at 1 44 10 pm" src="https://cloud.githubusercontent.com/assets/4267825/12590847/f9a3e2b0-c432-11e5-9068-5948b6f144aa.png">

#### Q&As

Q&As are written and published on the website. They look like this:

<img width="1059" alt="screen shot 2016-01-26 at 1 46 28 pm" src="https://cloud.githubusercontent.com/assets/4267825/12590975/9ce28594-c433-11e5-8e0a-634913890a0d.png">

They have categories and can be connected back to the regs sometimes:

<img width="753" alt="screen shot 2016-01-26 at 1 46 56 pm" src="https://cloud.githubusercontent.com/assets/4267825/12590986/ab2dec42-c433-11e5-9ccd-9f46a28fa38b.png">

<img width="788" alt="screen shot 2016-01-26 at 1 50 22 pm" src="https://cloud.githubusercontent.com/assets/4267825/12591008/c6206f66-c433-11e5-95e9-c7950ea7357a.png">

The are also published in the reg reference guides where they have letters and numbers:

<img width="230" alt="screen shot 2016-01-26 at 1 51 39 pm" src="https://cloud.githubusercontent.com/assets/4267825/12591045/f44166d4-c433-11e5-9812-770620aca326.png">

#### Newsletters

Newsletters are published in PDF form as well. They have some structure, but not much. Here is what a firearms newsletter looks like:

<img width="782" alt="screen shot 2016-01-26 at 1 54 26 pm" src="https://cloud.githubusercontent.com/assets/4267825/12591149/69951502-c434-11e5-8804-5efc18c07d64.png">

And here is an explosives newsletter:

<img width="798" alt="screen shot 2016-01-26 at 1 56 04 pm" src="https://cloud.githubusercontent.com/assets/4267825/12591219/bdecaa16-c434-11e5-861a-1b58c044e678.png">

Within paragraphs, regs, usc, and rulings can be associated:

<img width="350" alt="screen shot 2016-01-26 at 1 54 20 pm" src="https://cloud.githubusercontent.com/assets/4267825/12591231/cc137f20-c434-11e5-91bd-d0c8272663dc.png">

**Comment by jehlers** [comment]
Round 2 sketching starts here! Focusing on where we can cross reference different types of documents!

**Comment by Journerdism** [comment]
![img_1483](https://cloud.githubusercontent.com/assets/406607/12594259/2e1a364c-c443-11e5-9bac-3fd9018de24f.JPG)
![img_1484](https://cloud.githubusercontent.com/assets/406607/12594261/3013e844-c443-11e5-8338-0c910ed0d2d3.JPG)

**Comment by jehlers** [comment]
_First idea:_ **Bring link to and excerpts of the ruling into the center area where the regulation text exists.** It will take users out to the ruling reader, but it will at least be connected to the paragraph it refers to with some intro to what the ruling is. Maybe only do this with current rulings?

![img_4508](https://cloud.githubusercontent.com/assets/4267825/12594727/782d5bd6-c445-11e5-9225-658bbfe737e2.JPG)

_Second idea:_ Related to the first idea, but a little broader. **Since a lot of these reference materials reference a whole section rather than just a paragraph, we could start each section with a box that lists all the things that refer to that section.** Maybe its collapsible if there are a lot of things referencing that one section. Some links could be external, some would link out to the different content type readers.

![img_4509](https://cloud.githubusercontent.com/assets/4267825/12594785/d7abd844-c445-11e5-983f-2cca6691716f.JPG)

_Third idea:_ **Newsletters could be presented as PDFs.** They are so formatted, that it may not be work trying to take the text out. Not all the text is useful, but people are used to what parts of newsletters are useful to them. Maybe we could curate topics that would allow people both to search and maybe jump to parts of the pdf?

![img_4510](https://cloud.githubusercontent.com/assets/4267825/12594837/0c29cec8-c446-11e5-80c9-88d627cae7d2.JPG)

_Last thought:_ It's self explanatory.

![img_4511](https://cloud.githubusercontent.com/assets/4267825/12594852/1d261aa6-c446-11e5-83aa-3ed02fd65916.JPG)

#### Notes from the discussion after the sketching session.

**Where do we draw the line in terms of which documents we want to bring into eRegs?**

_Short answer:_ We don't know yet, but we have some hunches.

**Definitely want to bring it:**
- Rulings are obviously the most important document that ATF has after regulations. They are meant to be more closely associated with the regs. They are also the most structured documents which will make it easier to bring them in.
- Q&As are short and simple. They are plain language which really makes them useful. We do have some questions around if we would want to duplicate the content and show the text in this tool, or link out to where the content lives on atf.gov.

**Maybe:**
- Newsletters will be hard. We know they are really useful and hard to search, so we want to help, but they will need a lot of work to bring them in. Maybe we can figure out a way to tag them better and still reference them in the right places, but they would be linked out to the PDFs.
- Open letters seem less important, but we need to talk more about them.

**Comment by brittag** [comment]
Much like Jen's sketches, I'd like to find ways to bring cross-references to other kinds of material into the main column, possibly with boxed structures similar to the current cross-references to flyers.

I'd also like to find a way to provide an automatic overview of the contextual material available for a section - so that you don't have to scroll through the entire text of the regulation to find the plain-language supporting references available for that regulation.

It makes sense to me to integrate the most important and structured parts (such as Q&As and rulings) into the main column, and provide simple less-structured right-sidebar links to additional less-structured information such as recent open letters and newsletters.

![img_6097](https://cloud.githubusercontent.com/assets/391313/12598781/47b25c62-c441-11e5-80ef-585b6e2cb967.JPG)

**Comment by cmc333333** [comment]
![new doc 4_1](https://cloud.githubusercontent.com/assets/326918/12627073/d6e6afaa-c509-11e5-90f4-1f02d7f782cb.jpg)
Q&As live inline with the reg as they are generally short; they have no other page within eRegs

![new doc 4_2](https://cloud.githubusercontent.com/assets/326918/12627103/fec326a2-c509-11e5-99c3-5c19e1fe90aa.jpg)
We present rulings as largely plain text, but allowing for some citations and perhaps definitions. We can pull out some form of meta data into the RHS

![new doc 4_3](https://cloud.githubusercontent.com/assets/326918/12627075/d6eaa376-c509-11e5-8771-d3485f4f3509.jpg)
For open letters, newsletters, and other forms of content, we can build a system which allows ATF to maintain connections manually. This is similar to the existing poster links, but without requiring templates be modified. Open question: where do these files live?

**Comment by jbarnicle** [comment]
![photo 2](https://cloud.githubusercontent.com/assets/737400/12627992/9c6784ce-c506-11e5-90ee-ee3acdb53e5e.JPG)

Excuse the horrible lighting

**Comment by jehlers** [comment]
Lot's of great ideas! Will have more validation post Monday's workshop and will be able to move forward.
