### ISSUE TITLE
Slightly inconsistent spacing in external link indicators

### ISSUE THREAD

**Issue by brittag** [18F/atf-eregs#275]
While reading https://atf-eregs.18f.gov/478-76/2014-18392#478-76 I noticed that the second and third external link icons have slightly odd spacing, while the first external link icon looks normal (in Chrome):

<img width="903" alt="screen shot 2016-01-20 at 11 57 35 am" src="https://cloud.githubusercontent.com/assets/391313/12462494/74813038-bf73-11e5-8cb5-d1c7d5c4810d.png">

Not sure what the difference is between those links - interesting!

**Comment by cmc333333** [comment]
Not positive, but I'd bet the external citation parser is including the following space when it's parsing groups of citations. We don't have this problem for internal citations (e.g. "See section 478.76(a), (b), and (c)(4)"), so that might be a good model to follow.

**Comment by vrajmohan** [comment]
Fixed by https://github.com/18F/regulations-parser/commit/26c56c6ac5d3eab2cf2075878f19fca336bf2466
