### ISSUE TITLE
Implementing styles across the site

### ISSUE THREAD

**Issue by jehlers** [18F/atf-eregs#294]
Creating an issue to keep track of small tweaks throughout the next sprint as @jbarnicle and I work on implementing the new ATF styles. 

Based on #214 cc @xtine

**Comment by jehlers** [comment]
So far I only have a few small spacing notes on the universal homepage:

1. Before the footer hits, can we pad it or give a margin below the "Learn more...>" link? It would be great to have the same white space there as is above the "Title XX" text (between the "hero space" and the "Title XX" text)
2. In the hero - there should be a little more space between "A platform to read..." and the "eRegulations makes..." sentence - in the mock up I have it as 30px of visual space. I know that margins from the font/text mess with padding numbers so it probably needs some weird number. Maybe double it? We can see how it looks from there?
3. The computer illustration can be hidden a little on the bottom. So if we push it down so the top starts around where the top of the text starts. Like on the CFPB version.

**Comment by jbarnicle** [comment]
4) Per @jehlers I think we do want to bump the titles "General." to small text instead of super small

**Comment by jehlers** [comment]
Yes, in the table of contents.

**Comment by xtine** [comment]
Have any of these style updates been applied yet? Do you need any assistance @jbarnicle ?

**Comment by jbarnicle** [comment]
@xtine I'm doing a bunch of refactoring at the moment.  I think I'll be at a point tomorrow where it will be a point where you can jump in - would be great to have a second set of eyes.

**Comment by jehlers** [comment]
Ok! @jbarnicle just updated a lot so here are my list of tweaks:

#### Universal homepage

- [ ] Spacing issues listed [above](https://github.com/18F/atf-eregs/issues/294#issuecomment-176401858) still stand.
- [ ] "Title XXVII Alcohol, Tobacco Products and Firearms" should be bold (technically the H5 style).
- [ ] "About eRegulations" should also be bold (technically the H3 style).
- [ ] The "New amendment" warnings and links should be H5 as well (Lato Bold 16px but keeping their coloring). 
- [ ] @donjo also has a PR in to adjust the "New amendment" alert's spacing.

#### Headers 

- [ ] In the global (dark blue) header, "eRegulations" , "About" , and "Regulations" all look like they are fake bolded as opposed to using Lato Bold.
- [ ] In the grey-blue sub-header, "Subpart A | Section #" and the "Effective date" also look fake bolded as opposed to Lato Bold.

#### Main regulation content

- [ ] Merriweather body copy needs more line-height. Based on the web design standards, it should be font size: 15px with **line-height: 26px**. We double check on how that looks once it is implemented.
- [ ] "NOTES" do not need to be indented under the paragraph they are related to. They should match the indent of the paragraph above them, if possible.
- [ ] This may change based on the first check bullet in this main regulation content list. This also might best be tweaked during a screen hero session. But the spacing between paragraphs seems a little off. A good example of this is in the definitions section: 

<img width="660" alt="screen shot 2016-02-09 at 11 50 14 am" src="https://cloud.githubusercontent.com/assets/4267825/12923329/50e6fce2-cf23-11e5-8578-31089ef61f8a.png">

See how the (a) paragraph has the same spacing above it as the H3 level heading? But the paragraphs without an (a) marker that follow an H3 level headings have no extra space before them? We should make this kind of spacing more consistent across all heading levels.

I'm holding off looking at the Regulation timeline and search tabs, and the right sidebar because @jbarnicle said he's still working on those. I also am assuming that we will focus on the regulation landing pages when the new designs and @brittag's new content are implemented.

**Comment by jbarnicle** [comment]
Thanks @jehlers.  Firebug (debugger on Firefox) tells me there isn't any fake bolding going on in the headers - but I will double check to make sure.   I put together this codepen containing most of the relevent styles - this might help in determining if there is any fake bolding going on.

http://s.codepen.io/jbarnicle/debug/XXyydV

**Comment by jbarnicle** [comment]
@jehlers I tweaked some of the spacing issues - minus the image part.  It's a background image so that one might be tricky.  I also didn't touch New Amendment - was going to look into where the pr stood on that one.  The Merriweather line height should be good now.  Unfortunately - it doesn't look like those fake bolds are fake.   I pushed the latest to my instance.  Gong to visit help / search / sidepanel styles now.

**Comment by jehlers** [comment]
@jbarnicle Just checked out the codepen, everything looks good there!

The css isn't loading for me right now, so I can't look at the header or merriweather line-height right now. Let me know when that's fixed, and I'll take a look then!

**Comment by jehlers** [comment]
@jbarnicle Looking good! I've checked off what's working above, and adding some comments here:

> Before the footer hits, can we pad it or give a margin below the "Learn more...>" link? It would be great to have the same white space there as is above the "Title XX" text (between the "hero space" and the "Title XX" text)
^^ Still needs a little work along with the placement of the computer illustration.

- We've talked about the fake bolding that still looks like its happening in both of the headers.

- Should we plan to hop on a hangout or something today/tomorrow to work on spacing between paragraphs?

- Still trying to find an example of a Note to check.

**Comment by jehlers** [comment]
- [ ] The light gray line above "Compare this with..." in the regulation timeline isn't visible over the light blue. Can we make it white?

![screen shot 2016-02-10 at 1 42 33 pm](https://cloud.githubusercontent.com/assets/4267825/12957840/c341766c-cffc-11e5-93d8-ea408d290ff1.png)

**Comment by jehlers** [comment]
Sorry also just noticed this (which I don't think was happening before). Looks like worksans or slabo 13 is back in the footer:

![screen shot 2016-02-10 at 1 48 11 pm](https://cloud.githubusercontent.com/assets/4267825/12957906/036a8670-cffd-11e5-8e1a-3d52882d5c33.png)

You can tell by how the lowercase "l" has a little lip at the bottom, whereas the Lato lowercase "l" does not.

**Comment by jbarnicle** [comment]
Hey @jehlers -

- Fixed the footer.
- Bumped the "General" text to small text.
- Made the line above "Compare this with.." white

Also - you can start looking at the sidebar / search / history areas and noting any issues you see there.

I don't know what else to do about the fake bolding - maybe @xtine can compare the fonts in the codeine and my instance and see if she sees anything.

![screen shot 2016-02-10 at 3 14 56 pm](https://cloud.githubusercontent.com/assets/737400/12962014/1c306632-d009-11e5-9a3e-6a551567e402.png)

**Comment by jehlers** [comment]
Can we un-dot the white line above "compare this with?" I had no idea it was dotted and not it looks stranger than not being there haha.

**Comment by jehlers** [comment]
From what I can tell right now, everything looks good in the regulation timeline and search tabs! When we look at paragraph spacing tomorrow, we should also look at the defined terms that pop up in the right sidebar. 

One other thing that I'm realizing:

- [ ] Can we bump up the next/back buttons and text? It's looks small. They should probably be the body size of lato, so 16px?
- [ ] And add some padding/margin at the bottom so the page doesn't end EXACTLY when that text ends.

![screen shot 2016-02-10 at 5 47 16 pm](https://cloud.githubusercontent.com/assets/4267825/12964510/8a6c6d16-d01e-11e5-9f62-e26ac7b08576.png)

**Comment by jbarnicle** [comment]
Ok @jehlers - I just pushed these changes to https://atf-redesign-work.apps.cloud.gov/

- Un-dotted the white separator
- Bumped the prev / next links to 1em (16px)

I'll review the remaining outstanding changes and we can circle back tomorrow.

**Comment by cmc333333** [comment]
@jehlers with the changes in #393, which are all available on the demo site, can we close this?

**Comment by jehlers** [comment]
> The "New amendment" warnings and links should be H5 as well (Lato Bold 16px but keeping their coloring). 

Is the only thing that wasn't touched. But it's not a big deal, so yes.
