### ISSUE TITLE
Munitions List: Frontend Paragraph Markers

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#301]
With a few exceptions, we currently rely on `li`s to generate the appropriate paragraph markers for us. To complete the munitions list, however, we'll need to both _skip_ paragraphs and include abnormal paragraph markers. For example, we may be able to generate markup that looks like:

```
<ol>
    <li><p><span class="marker">a.</span> Paragraph a, here.</p></li>
    <li><p><span class="marker">b-d.</span> RESERVED</p></li>
    <li><p><span class="marker">e.</span> Paragraph e</p>
        <ol><li><p>Paragraphs f and g are missing for some reason</p></li></ol></li>
    <li><p><span class="marker">h.</span> Paragraph h</p></li>
</ol>
```
And we want to display it like:
```
  a. Paragraph a, here.
b-d. RESERVED
  e. Paragraph e
     Paragraphs f and g are missing for some reason
  h. Paragraph h
```

Note particularly that all of the paragraph markers are aligned by their period (/ first letter in their content); they "grow" to the left. Don't worry about the nested paragraph -- that's already displayed correctly

There's been some subpar solutions to handle this in the past. For example, the US Code in https://atf-eregs.apps.cloud.gov/478-103/2014-18392#478-103-b-p1-p5 uses absolute positioning and a fixed width indent. The fixed width part is the major problem here, as, should the marker be too wide (as will occur with `b-d.`), the marker would cover the paragraph text.

**Comment by xtine** [comment]
Will we always know how wide the "b-d" type markers will be? I'm wondering if a solution could be as simple as to set the markers to the largest width and then just have text-align: right so the periods always stay flush to the right side.

**Comment by cmc333333** [comment]
Hypothetically, we'll know how wide _in characters_ the markers are. What do you think about ignoring the actual width and just setting an arbitrary maximum, like 10em here:

```less
li p {
    position: relative;

    .paragraph-marker {
        position: absolute;
        text-align: right;
        left: -10em;
        width: 9.5em;     /* simulates a .5em padding */
    }
}

**Comment by xtine** [comment]
Yeah @cmc333333 I think what I was describing with "largest width" could also work with just setting a width and having it set to the right text-align. Is this data available on a local instance so I can style test this yet?

**Comment by cmc333333** [comment]
@xtine I think the next step would be to apply this site wide -- null out the lower, roman, etc. subclasses here: https://github.com/18F/regulations-site/blob/master/regulations/static/regulations/css/less/module/paragraph-markers.less and make the `stripped-marker` class (rather than `.paragraph-marker`) visible and right aligned. A few things to verify here:

* Generally, does this look right?
* Does it look alright if you modify one of the paragraph markers to be something wide like "b - d."
* Collapsed markers, where a paragraph has no text, only subparagraphs. See e.g. https://atf-eregs.apps.cloud.gov/447-41/2015-12992#447-41-c-1
* Browser support (though I think we're safe here)
* Mobile (again, I think we're safe)

We don't have any data yet that includes these types of markers, but will soon; in the meantime, we can test the rest of the site and manually. Ping us in slack if you need pointers for how to access the live or demo data locally.

**Comment by cmc333333** [comment]
Heads up @xtine, looks like we need to vertically center these when the text has a keyterm:

<img width="655" alt="screen shot 2016-02-08 at 6 38 47 pm" src="https://cloud.githubusercontent.com/assets/326918/12903151/87433566-ce93-11e5-9a9d-9a8c8dc01dda.png">

**Comment by cmc333333** [comment]
All looks good

**Comment by cmc333333** [comment]
Great work @xtine
