### ISSUE TITLE
Definitions for more specific terms link show definitions for more general terms instead

### ISSUE THREAD

**Issue by vrajmohan** [18F/atf-eregs#302]
In https://atf-eregs.18f.gov/555-222/2015-25190#555-222-p1, when clicking on *Display fireworks*​ or ​*Consumer fireworks* to view definitions, one is presented with the definition of *fireworks* instead. Note that specific definitions for *Display fireworks*​ and ​*Consumer fireworks* do exist.

<img width="1004" alt="screen shot 2016-01-29 at 5 12 24 pm" src="https://cloud.githubusercontent.com/assets/2066204/12689542/8c15378c-c6ab-11e5-98c2-b49b5f509474.png">

**Comment by cmc333333** [comment]
Resolved with #403
