### ISSUE TITLE
compile_frontend touchups

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#31]
* Add `frontend_build` to gitignore so that it's not pushed with cf (the dir is almost a quarter a gig)
* Add settings for finding the new static files
* I had to move `static/*` into `static/regulations/*` manually

**Comment by tadhg-ohiggins** [comment]
The third bullet point is addressed by https://github.com/18F/regulations-site/pull/28.

**Comment by tadhg-ohiggins** [comment]
The first bullet point is addressed by https://github.com/18F/atf-eregs/pull/49

**Comment by cmc333333** [comment]
18f/regulations-site#32 and #51 accounted for bullet 2
