### ISSUE TITLE
Back button to landing page does not work

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#33]
In a modern browser (i.e. one w/ push state)
1. Go to the root (universal landing page)
2. Click a regulation -- you'll get to the regulation's landing page
3. Click a section in the TOC
4. Click the back button -- the url changes to the landing page but the page content does not

**Comment by jbarnicle** [comment]
Right now the landing page of a regulation is not mapped to any model.  An approach would be to map it the same way we map other sections - using class selectors.   Here is what the section for 447.1 looks like:

URL:http://xxxx/447-1/2014-18842#447-1
<section id="447-1" class="reg-section section-focus" tabindex="0" data-permalink-section data-base-version="2014-18842" data-page-type="reg-section" >

The proposal would be treat the landing page as a special case of section.  The landing page for 447 would then look like:

http://xxxx/447
<section id="447" class="reg-section section-focus" tabindex="0" data-permalink-section data-base-version="" data-page-type="reg-section" >

This would mitigate the amount of "special case" code for the landing pages.  This however does require that landing content be retrievable via a partial in the albeit unlikely case that someone navigated back to the home page using the back button after a complete page refresh.

Home-Page->Landing->Section->About->{BACK}->{BACK}

@cm - is this more in line with the approach you were envisioning?

**Comment by cmc333333** [comment]
@jbarnicle the JS side of this appears to all be working. Good to close?

**Comment by jbarnicle** [comment]
I believe so
