### ISSUE TITLE
"Search" highlight is a bit off

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#342]
<img width="317" alt="screen shot 2016-02-09 at 12 40 38 pm" src="https://cloud.githubusercontent.com/assets/326918/12925053/7d276f06-cf2a-11e5-94c6-252ba7edcd47.png">

You can see the magnifying glass isn't highlighted correctly

**Comment by jbarnicle** [comment]
I'm seeing this in demo / live - but not in my local.  Might have been righted as part of the font changes.

**Comment by jbarnicle** [comment]
This looks fixed in https://atf-eregs-demo.apps.cloud.gov/ now - or am I missing something?

**Comment by cmc333333** [comment]
:+1:
