### ISSUE TITLE
Footnotes jump link jumps to wrong location

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#348]
When jumping up from a footnote (e.g. in /555-223/2015-25190), we scroll to a spot a bit below (the header hides the text we meant to jump to). IIRC, this is due to paragraphs having negative padding or something strange along these lines to account for scrolling under the header.

We'll need to either fix this outright or remove the jump links in the footer before the release.

**Comment by vrajmohan** [comment]
Closed by 18F/regulations-site/pull/92.
