### ISSUE TITLE
508 Compliance

### ISSUE THREAD

**Issue by jbarnicle** [18F/atf-eregs#366]
Run ATF site thru 508 compliance checking tools and address any issues raised.   Our accessibility documentation can be found here: https://pages.18f.gov/accessibility/

**Comment by Journerdism** [comment]
I was running some browser tests and I think we need to add line height for the H2 class Hero-header. On mobile, the “A platform to read regulations” breaks to two lines is crashing into each other

![screen shot 2016-02-22 at 12 43 30 pm](https://cloud.githubusercontent.com/assets/406607/13227126/12e9ebee-d963-11e5-9c83-be95f9867dd8.png)

**Comment by cmc333333** [comment]
The scrunchy text will be resolved by #394

**Comment by cmc333333** [comment]
Merged
