### ISSUE TITLE
Rulings MVP in the sidebar

### ISSUE THREAD

**Issue by jehlers** [18F/atf-eregs#376]
The Rulings MVP feature should live in the sidebar the same way the CFPB SxS tool works.

- It should default to open and be gold IF that section has related rulings. 
- The rulings should be listed in order starting with the most recent.
- The user can close the module if they want to.
- The links take users out to a new tab with the PDF of the ruling.

![rulingsmvp-01](https://cloud.githubusercontent.com/assets/4267825/13179938/6badd9b4-d6f4-11e5-85df-9df88c607e48.png)

I can post more about the specific styles later today.

**Comment by cmc333333** [comment]
Still needs 18F/regulations-site#102 and #379.

**Comment by cmc333333** [comment]
All merged
