### ISSUE TITLE
Missing icons in navigation sidebar on Windows

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/atf-eregs#39]
Some of our ATF users can't see the icons at the top of the navigation sidebar, as shown in this image.

![image003](https://cloud.githubusercontent.com/assets/2626258/10024706/574d7752-610d-11e5-9932-2afd66cdb6e7.jpg)

**Comment by cmc333333** [comment]
What we know: users see this in IE11,  Firefox ESR 31.2.0, inside a rather restrictive firewall

**Comment by jpyuda** [comment]
I'd guess they're blocking web fonts.

**Comment by cmc333333** [comment]
Firefox 31.2.0 works for me. +1 to them blocking web fonts

**Comment by tadhg-ohiggins** [comment]
The text/header fonts in their screenshot don't match what they should be seeing, so another +1 to them blocking web fonts.

**Comment by Journerdism** [comment]
I tested on Firefox 40.03, Chrome 45.0.2454.93 and Safari 8.0.8, all on a Mac on a neutral (non-gov) network with no issues.

**Comment by Journerdism** [comment]
Here's the most recent update from Hadiza yesterday:
"I switched the compatibility modes and it didn’t render either so it may be an issue. I’ll check with our IT folks and confirm if that is the case.  Thanks for the quick response!"

**Comment by cmc333333** [comment]
I'm going to go ahead and close this as we diagnosed the problem to ATF's network restricting web fonts.

**Comment by jehlers** [comment]
Most recent update from Hadiza is that they could not whitelist the icon font. 

We need to switch out the navigational icons in the left drawer to SVGs so that even people who are internally using ATF's machines can see and use the navigation.

**Comment by cmc333333** [comment]
This was resolved with 18F/regulations-site#96
