### ISSUE TITLE
Explicit label in AMDPAR and MARKERLESS

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#40]
https://www.federalregister.gov/articles/2009/01/14/E9-578/commerce-in-explosives-amended-definition-of-propellant-actuated-device-2004r-3p#p-amd-3 and https://www.federalregister.gov/articles/2014/08/11/2014-18842/technical-amendments-to-regulations#p-amd-51 refer to specific, markerless paragraphs. Unfortunately, using the `[label:555-11-p65]` syntax does not work as the paragraph is parsed as `555-11-p1`.

`regparser.notice.changes` has some functions around "candidates" and misparsed changes which would be good to leverage.

**Comment by theresaanna** [comment]
This issue has been resolved by the annual editions work that @cmc333333 has done.

**Comment by theresaanna** [comment]
Nevermind! Still a current issue. https://www.federalregister.gov/articles/2015/10/02/2015-25190/technical-amendments-to-regulations-correction#h-20

Would be resolved by the next annual edition, but who has that kind of time?

**Comment by cmc333333** [comment]
Closed by 18f/atf-eregs#114
