### ISSUE TITLE
Broken Footnotes

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#426]
Footnotes are being collected on the wrong section (in addition to the correct section).

For example, on `555-2`:
<img width="665" alt="screen shot 2016-03-09 at 2 15 53 pm" src="https://cloud.githubusercontent.com/assets/326918/13647306/75dcbc18-e601-11e5-9509-f97bc7692180.png">

I'm guessing there's a substring match fail here -- we should be comparing `label` components rather than `label_id`s.

**Comment by vrajmohan** [comment]
Fixed by https://github.com/18F/regulations-site/commit/58cb8c6bc925dd87631d202a4c47d4b71002d3c2
