### ISSUE TITLE
ATO prep

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/atf-eregs#446]
According to https://docs.google.com/document/d/1EG-tzRkYZ7_3gLd_hxA2wkV1st_-g8uANdKLnXwL0sE/edit our ATO expires 30 Nov 2016, but we thought that they had paid for longer than that.
- [ ] If an updated document reflecting the extension does not exist, create it.
- [ ] Link to the updated document with the extended date from this issue.
- [ ] Update the title of this issue to reflect the actual expiration date.

**Comment by tadhg-ohiggins** [comment]
Wrong repo, deleting!

**Comment by Journerdism** [comment]
Noting this: https://github.com/18F/Infrastructure/issues/694

**Comment by NoahKunin** [comment]
Now I'm confused - is ATF paid up on cloud.gov?

**Comment by Journerdism** [comment]
@NoahKunin Yes, for 2017 they renewed.

**Comment by micahtaylor** [comment]
Noting that there is an open question of who will own the ATO. 18F or ATF. My impression is it, ideally, should be ATF.

**Comment by micahtaylor** [comment]
Documenting the ATO conversation on slack -
https://gsa-tts.slack.com/archives/C08ULFU22/p1500999065983226

**Comment by micahtaylor** [comment]
If transferring to ATF via Jay Huie, 

> Mason Mcdaniel is the CTO over at ATF and is awesome. Would suggest - whenever you do talk to ATF - you ask if you can meet w/ him to discuss the work, ATO, anything. He’s a cloud :fan: and gets it.

**Comment by yowill** [comment]
Two options for ATF ATO going forward (to be discussed with DOJ folks Thursday (?) or whenever the meeting gets scheduled):
- ATF takes on compliance responsibility for ATF eRegs, using cloud.gov's FedRAMP JAB-approved PATO to make this process easier/faster. (cloud.gov takes care of most compliance controls for an ATO)
- 18F redirects some efforts during this well-timed engagement to ensure compliance, possibly by creating the required documentation or by converting the sites to a set of static pages (vastly reducing the attack service and allowing GSA to continue owning the ATO for the published static site at no additional cost).

**Comment by micahtaylor** [comment]
Phone call outcome:
ATF has the takeaway to discuss among themselves their staffing capacity to take on the ATO and maintenance related or budget to contract with us to keep the ATO and maintain.

**Comment by yowill** [comment]
Thomas is going to connect with Micah and Kimber to work on the SSP software stack. Email connecting the three of them is in those folks mailboxes.

**Comment by micahtaylor** [comment]
GSA will continue to manage the ATO. Closing this and opening new issue to track implementation.
