### ISSUE TITLE
Change defined term link colors

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/atf-eregs#449]
Change the colors of the defined terms in the regulations.

I'm pretty sure that adding these CSS elements to https://github.com/18F/atf-eregs/blob/master/atf_eregs/static/regulations/css/scss/module/custom/_typography.scss will do it, but I'm not sure what the colors should actually be.

```
.definition,
.definition:link,
.definition:visited {
}

.definition:hover,
.definition:active {
}

.definition.active {
}
```

**Comment by cmc333333** [comment]
In thinking about the above, try to delineate what should be part of "core" and what's an ATF-specific thing, too.

**Comment by jehlers** [comment]
Sorry for the late response.

This is the "current" terms color on production now (via inspect):

<img width="318" alt="screen shot 2016-09-28 at 12 27 52 pm" src="https://cloud.githubusercontent.com/assets/4267825/18923340/da126f94-8579-11e6-9dbd-eec59eec4c3d.png">

That ^^ #D1D3D5 is the one we should keep for the "core" platform.

For ATF's theme we should switch that gray to #767676

How's that? Did I miss anything?

**Comment by tadhg-ohiggins** [comment]
Hmm; #D1D3D5 is the `$history_drawer_border_color`, but the border-bottom for the definition links is set to the `$gray_light` variable, which is #D8D8D8, so I'm slightly confused about which variable to change.

**Comment by cmc333333** [comment]
Skimming through where `$gray_light` is used, I see lots of borders and some text in the header and sidebar. Given how close the two colors are, lets try swapping out `$gray_light` and pushing that to demo for @jehlers to spot check? I'd like to delete the `$history_drawer_border_color` (and other one-offs) if possible, but that may be out of scope.

**Comment by tadhg-ohiggins** [comment]
No-really-this-time fixed by <https://github.com/18F/atf-eregs/pull/454> and <https://github.com/eregs/regulations-site/pull/467>.
