### ISSUE TITLE
Research questions workshop

### ISSUE THREAD

**Issue by carodew** [18F/atf-eregs#470]
- [x] conduct workshop
- [x] write up notes
- [x] publish notes on research wiki

**Comment by carodew** [comment]
Added notes to research wiki 
- https://github.com/18F/atf-eregs/wiki/eRegs-user-research-workshop-results

Added link to homepage
- https://github.com/18F/atf-eregs/wiki

**Comment by carodew** [comment]
![external-users](https://user-images.githubusercontent.com/10144074/28217881-becb4dde-6884-11e7-8192-05a819e9fb2e.png) (adding to create link)

**Comment by yowill** [comment]
DONE!
