### ISSUE TITLE
Sketch out solution for fetching Ruling/etc. info

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#474]
Once we have Ruling, FAQ, etc. from the Drupal API (#473), we need to figure out how to merge it with our rendering.

Some options:
* If it's easy to query, include the code in the Django site
* If it's easy to query, include the code in JS (i.e. client-side render)
* If it's difficult to query, run a batch process in the Django site
* If it's difficult to query, run a batch process of the parser

**Comment by carodew** [comment]
Leaving a note here for us to consider when we get into the UI design phase – 

![image](https://user-images.githubusercontent.com/10144074/27962268-5f4fe55c-62ff-11e7-86a2-dee849b4d9c6.png)

I think it's great that the Rulings bar will appear gold when rulings are there, but I don't think that's necessarily clear without reading the About page. I found myself clicking open the Rulings bar each time I navigated to a new section to see if anything was there (not knowing I was looking for a change in color). The other issue is that this is likely ineffective for color blind users, and we should consider a non-color dependent way of communicating this. 

Possible options to explore and validate – 
- include a badge counter on the header that shows the number of rulings (including 0 rulings) 
- Once a user has expanded the Rulings section on one page, persist that setting when they navigate to new pages, until they manually close it again.

**Comment by cmc333333** [comment]
@carodew moved the interface discussion to a new ticket; this one's focused on retrieving the data.

**Comment by cmc333333** [comment]
Based on discussion with @tadhg-ohiggins, the current strategy is to write a Django management script in the `atf_eregs` app which will fetch data and insert it into the database (skipping the parser). We will run this script at some fixed, recurring interval. It will need to clear the appropriate data when inserting new content.

We can spin out these tasks into additional issues.
