### ISSUE TITLE
Implement new sidebar/additional resources design

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#500]
Implement @micahtaylor's sidebar designs: https://github.com/18F/atf-eregs/issues/477#issuecomment-320088228

As ATF doesn't have an API ready, we can start with just Rulings.

**Comment by carodew** [comment]
I was writing this as a separate story but it belongs with this one, so just adding it here as a comment. This would should ideally fulfill this user story – 

As an licensee, I want to easily find and view a form when it's referenced in regulation text. 

## acceptance criteria 
* Whenever a specific form (for example, Form 4473) is referenced in the main content area, provide a link to that form.

**Comment by cmc333333** [comment]
@carodew heads up that we won't have form data yet; we'll start with the Rulings data.

**Comment by carodew** [comment]
@cmc333333 is it worth breaking that out into a separate issue then, so it doesn't get lost?

**Comment by cmc333333** [comment]
I think it'll be a task for ATF more than for us. Maybe think about it as: we're building an interface, but the data tagging all comes from ATF. I don't think they'll have all the data tagged by the end of our engagement.

**Comment by carodew** [comment]
I think we just want to be sure that what we build can accommodate that, right? I think we can note that. I like to think of units of work as units of value to the user which is why I prefer to write them in this format.

**Comment by cmc333333** [comment]
Alrighty, how about:

## acceptance criteria
* eRegs displays associated documents (beginning with Rulings but extendable to other documents, like forms) in the right side per the design in #477

**Comment by micahtaylor** [comment]
Updated ideals for the right hand sidebar.

<img width="721" alt="related docs" src="https://user-images.githubusercontent.com/671894/29188935-606110c4-7dda-11e7-9073-2295ed6b2563.png">

**Comment by carodew** [comment]
Bringing this to the thread so it's all in one place. ATF is requesting the following headers for related docs: 

Rulings / Procedures
Forms
FAQs / Newsletters
Open Letters / Circulars
Other Resources

I have no indication from users which order/groupings they prefer but that's definitely something I'd recommend usability testing in a future engagement and not sure if we want to suggest an alternative that might be more flexible over time. 

If we do go with these groupings I'd recommend not using a `/` as a connector but actually spell out the word `and` and also use sentence case.
