### ISSUE TITLE
Swap homepage image

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#507]
> Add picture of ATF HQ (provided by ATF) to the top of home page (instead of computer)

We'll need to get an image from ATF.

**Comment by carodew** [comment]
Not sure what user need this addresses?

**Comment by cmc333333** [comment]
The current image doesn't address any user needs, either :) Adding the ATF HQ graphic would at least keep with existing ATF branding.

Would this be a step down? If not, I think this would be a quick (though, low priority) win.

**Comment by tadhg-ohiggins** [comment]
Did they ever supply the image of HQ? Some work will be required to turn an image into something that can be dropped in as a replacement for the current one, I suspect.

**Comment by carodew** [comment]
The current image offers some type of quick preview of what to expect when they open a regulation.  It's also a fairly simple and clean illustration that projects a pretty modern and sophisticated look. These are probably relatively subtle benefits but we could do visual preference testing if we want to check to see how it impacts user experience. 

My fear with the building photo is that it could be visually more complicated, and any time you add visual complication you risk throwing off the entire visual hierarchy that help's guide a user's eye to the parts of the interface that are the mot important. I've also not seen the photo but if it's a low quality photo or has an aspect ratio that doesn't fit in the space, it could give the wrong impression (that the site is also low quality, for example, or hastily put together out of pieces that don't really fit). Last, most users aren't going to know what the ATF building even looks like, so the image most likely will just be confusing, which will add to cognitive strain for users who aren't sure why it's there. Trying to caption or explain the image to users in the UI adds even more information and cognitive load.

**Comment by cmc333333** [comment]
Replaced ny #538
