### ISSUE TITLE
Part-specific links

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#509]
> Additional resources to right column of page (including newsletters, licensing and registration, TTB and CBP links).

Need to get content from ATF

**Comment by cmc333333** [comment]
This would be static content, such as https://regulations.atf.gov/447 rhs's "Additional resources"

**Comment by tadhg-ohiggins** [comment]
From Andrew via email:

- [ ] The first one needs to go on Part 478 landing page.  It is for the “State Laws and Published Ordinances” with link:  https://www.atf.gov/firearms/state-laws-and-published-ordinances-firearms-32nd-edition. 
- [ ] The second one was for inactive rulings, etc. and that has not been developed on the ATF webpage as of yet.

**Comment by yowill** [comment]
Here's some that Andrew just sent over:

1)      Part 646 landing page – TTB Tobacco Information (https://www.ttb.gov/tobacco/index.shtml)
2)      Part 478 landing page – TTB Firearms and Ammunition Excise Tax (https://www.ttb.gov/firearms/index.shtml)
3)      Part 447 landing page – CBP Basic Importing and Exporting (https://www.cbp.gov/trade/basic-import-export) and State Department Export Controls (https://www.state.gov/strategictrade/)
4)      478.111 and 478.171 – CBP Basic Importing and Exporting (https://www.cbp.gov/trade/basic-import-export)
5)      479.111 and 479.114 – CBP Basic Importing and Exporting (https://www.cbp.gov/trade/basic-import-export)

**Comment by yowill** [comment]
MORE HOT LINKS FROM ANDREW! 

This should be all of them now:
 

- 555.141 – U.S. Pharmaceutical Convention (http://www.usp.org/)
- Part 555 landing page – Mine Safety and Health Administration (https://www.msha.gov/)
- Part 555 landing page – National Fire Protection association (http://www.nfpa.org/)
- Part 555 landing page – Pipeline and Hazardous Materials Safety Administration (DOT) (https://www.phmsa.dot.gov/)
- Part 555 landing page – U.S. Consumer Product Safety Commission (https://www.cpsc.gov/)

**Comment by cmc333333** [comment]
We can't do
> 478.111 and 478.171
> 479.111 and 479.114
> 555.141

as that content is dynamic. However, *ATF* can add those resources the same way they'd add Rulings, Forms, etc.

**Comment by yowill** [comment]
Okie dokie, I'll let them know

**Comment by yowill** [comment]
Andrew's response, "Yes, that makes sense.  Thank you."
