### ISSUE TITLE
Mention where data comes from in the about section

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#511]
> In the About section, state that e-Regs uploads information from the Federal Register in the top paragraph.

**Comment by carodew** [comment]
There does seem to be a user benefit in that those people we talked to who most trusted the information on the site understood where the data was coming from.

**Comment by yowill** [comment]
@tadhg-ohiggins ditto, this is completed with your most recent About changes, right?

**Comment by tadhg-ohiggins** [comment]
It's in production, closing.
