### ISSUE TITLE
Image swap

### ISSUE THREAD

**Issue by yowill** [18F/atf-eregs#538]
Here's the images provided that they'd like to test/swap for the computer. 
![istock_000074406419_medium](https://user-images.githubusercontent.com/406607/29791068-b2fad170-8c09-11e7-91b4-9e90ceef6ffb.jpg)
![istock_000049036242_medium 1](https://user-images.githubusercontent.com/406607/29791070-b2ff1a64-8c09-11e7-87c8-02b2a2cc949e.jpg)
![istock_000051699848_medium](https://user-images.githubusercontent.com/406607/29791067-b2f86c5a-8c09-11e7-9ed4-921e3b4eac38.jpg)
![istock_000027857942_medium](https://user-images.githubusercontent.com/406607/29791066-b2f750ea-8c09-11e7-84df-93dbe034be34.jpg)
![istock_000049036242_medium](https://user-images.githubusercontent.com/406607/29791065-b2f757e8-8c09-11e7-909d-a52270382dd7.jpg)
![istock_000012195550_small](https://user-images.githubusercontent.com/406607/29791069-b2fb00c8-8c09-11e7-8332-6889016feaf6.jpg)

**Comment by micahtaylor** [comment]
https://github.com/eregs/regulations-site/pull/507
