### ISSUE TITLE
Branding rework

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#539]
Per our planning conversation, @micahtaylor will run through a quick branding design studio to find low hanging fruit to make the app less "eRegs" and more "ATF". @tadhg-ohiggins's already worked on some of these designs.

**Comment by tadhg-ohiggins** [comment]
This is my first suggestion for copy tweaks on the home page:
![image](https://user-images.githubusercontent.com/2626258/29791784-09da3f06-8bf3-11e7-8e80-2227991e32e5.png)

**Comment by cmc333333** [comment]
Adding these notes as something we've mentioned or commited to:

> For instance, instead of “eRegulations or “Home Page” at the top, we may say “ATF Regulations.”

> We intend to change the “About” wording to something like “Getting Started” to satisfy some of the need here.

**Comment by yowill** [comment]
DONE!
