### ISSUE TITLE
Update ATF API URL

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/atf-eregs#560]
The related documents API is being updated, and its URL will change to https://www.atf.gov/api/v1.1/ereg/

We should change our code accordingly.

- [x] Test the staging URL (which we don't have yet) on our demo server.
- [x] Test the production URL on our demo server.
- [x] Push the production URL code to our production server.

**Comment by yowill** [comment]
@tadhg-ohiggins Is this finished/clear to close?

**Comment by tadhg-ohiggins** [comment]
Yup, closing.
