### ISSUE TITLE
555 - Table issues

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#67]
The annual editions vary a tad in their recreation of 555's tables (particularly, sections 218, 220, 222, 223, 224). I'm betting that most of these are formatting errors. See which can be automatically reduced via a preprocessing step

**Comment by cmc333333** [comment]
@tadhg-ohiggins here's another one about 555

**Comment by tadhg-ohiggins** [comment]
The new handling of EXTRACT, FTNT, and TTITLE seems to have fixed these inconsistencies.
