### ISSUE TITLE
Smushed table headers

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#70]
Tables with lots of columns tend to get smushed headers, e.g. 555.218
<img width="589" alt="screen shot 2015-11-05 at 6 08 35 pm" src="https://cloud.githubusercontent.com/assets/326918/10984568/444afe88-83e8-11e5-83d4-78073b2648fb.png">

While we can expand the space the table lives in somewhat (e.g. by floating the rhs info over it or making the rhs collapsible), a more general solution is probably in order.

@tadhg-ohiggins suggested a quick hack
> Is there a way to cheat with using `overflow: hidden` and `title`?
> So that the headers are chopped off at the borders but a tooltip appears when you roll over them? I’m not sure how reliable that is now, but it seems worth exploring.

I suggested a scrollable table.

There are no doubt other good options. Explore them and implement.

cc @ascott1 @jehlers

**Comment by ascott1** [comment]
> I suggested a scrollable table.

I think this may be a good option here, as it allows us to preserve the formatting from the regs.

**Comment by jehlers** [comment]
It is interesting that there are definitions in those headers. @cmc333333 when you say scrollable, do you mean left -> right?

**Comment by cmc333333** [comment]
@jehlers yep yep

**Comment by jehlers** [comment]
How does this work on paper?

**Comment by jehlers** [comment]
Thoughts on allowing the whole table to scroll as opposed to just the headers? Like here: https://www.atf.gov/explosives/555218-table-distances-storage-explosive-materials-high

**Comment by cmc333333** [comment]
@jehlers re: paper: Looks like hyphens and hope: http://www.gpo.gov/fdsys/pkg/CFR-2014-title27-vol3/pdf/CFR-2014-title27-vol3-sec555-218.pdf

re: scrolling: For sure, if the table were scrollable, it'd be the whole table at once. I think there's probably a way to implement it so it's more obvious that scrolling is the "right thing" to do.

**Comment by ascott1** [comment]
> Thoughts on allowing the whole table to scroll as opposed to just the headers? Like here: https://www.atf.gov/explosives/555218-table-distances-storage-explosive-materials-high

Yes, this is precisely what I was picturing.

**Comment by cmc333333** [comment]
@jbarnicle With #79 the whole page scrolls rather than just the table. This gives a very "pdf" feel, which we're certainly trying to avoid. Would you mind making only the table scroll?

Also, if you can think of some indicator that the user _should_ scroll here, that'd be awesome.

**Comment by jbarnicle** [comment]
Just making sure we're on the same page - I don't see the whole page scrolling, but I do see that it introduces scrollbar for the whole center column.  Is that what you are referring to @cmc333333?

**Comment by jbarnicle** [comment]
@cmc333333 - The atf example is interesting in that it behaves differently on chrome and FF (FF doesn't overflow).  We're looking for something along the lines of how chrome handles this I'm guessing.

**Comment by cmc333333** [comment]
@jbarnicle you're right -- we should aim for Chrome. The FF view, though nicely responsive, simply cuts off data if the window is shrunk too small

**Comment by cmc333333** [comment]
Related, there's a scroll bar for short sections which shouldn't exist:
<img width="1075" alt="screen shot 2015-11-17 at 4 26 23 pm" src="https://cloud.githubusercontent.com/assets/326918/11225403/f0b5bc04-8d47-11e5-9459-cde2fc458e16.png">

**Comment by cmc333333** [comment]
#106 resolved for ATF; just need to get the same into regulations-site and we can close this

**Comment by cmc333333** [comment]
Resolved in 18f/regulations-site#40
