### ISSUE TITLE
Elements and concepts that we need to handle for ATF regulations 555 and 478

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/atf-eregs#72]
EXTRACT (mostly handled)
EXAMPLE
HD (at lower levels than direct child of SECTION) (partially handled)
FTNT/FTREF

GPOTABLEs with multiple headers (we have a solution for this right now, simply reflecting the order of the headers, one before and one after the table; we haven't added any semantic information in the parser).

**Comment by cmc333333** [comment]
`FTNT/FTREF` decomposed into:
* Backend/data structure implementation + minimal UI (alt/title text) #55
* Better, though not final UI #75

**Comment by cmc333333** [comment]
Only missing concept is a `<TITLE />` tag in a `<GPOTABLE />`. Splitting that out into #105, otherwise, we've got all the new concepts.
