### ISSUE TITLE
Present EXAMPLE nodes appropriately in UI

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/atf-eregs#74]
The example nodes should have a `node_type` of `example`, and so -site is going to need to look for that and to perhaps present them differently—how we should present examples isn't entirely clear.

**Comment by tadhg-ohiggins** [comment]
I think this pull addresses this adequately, assuming that we don't need to call examples out stylistically: https://github.com/18F/regulations-parser/pull/112

I'll leave this open until we can all have a look at how 555.103 looks in the browser without any changes to -site.

**Comment by cmc333333** [comment]
:+1:
