### ISSUE TITLE
Present FTNT/FTREF nodes appropriately in UI

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/atf-eregs#75]
I think these will be adjacent right now, and again it's not clear how they should be presented.

**Comment by cmc333333** [comment]
Note that there's an implementation in section-by-section analysis that it'd make sense to at least resemble. E.g. http://www.consumerfinance.gov/eregulations/sxs/1026-1/2013-28210?from_version=2015-18239

**Comment by cmc333333** [comment]
Resolved in 18f/regulations-site#35
