### ISSUE TITLE
Present HD nodes appropriately in UI

### ISSUE THREAD

**Issue by tadhg-ohiggins** [18F/atf-eregs#76]
I think we're currently handling these reasonably well, but we should examine them and make sure we're happy with the current approach.

**Comment by cmc333333** [comment]
I'm going to go ahead and close this in favor of a 478-specific ticket, as ATF noted the extracts/examples in 555, etc. weren't a problem.

**Comment by jehlers** [comment]
@tadhg-ohiggins what are HD notes? :grin:
