### ISSUE TITLE
Add 18F Google Analytics snippet to code 

### ISSUE THREAD

**Issue by Journerdism** [18F/atf-eregs#80]
Here's the response from the Analytics team:
https://18f.slack.com/archives/g-analytics/p1447192071000020

Here's the snippet:
https://github.com/18f/analytics-standards#18f-team-standards-for-analytics

Here's the UA code:
UA-48605964-38

**Comment by cmc333333** [comment]
Note that there are already some settings for this which could be reused: https://github.com/18F/regulations-site/blob/master/regulations/settings/base.py#L133

**Comment by cmc333333** [comment]
Everything's merged
