### ISSUE TITLE
27 CFR 447 2014-06778 depth problem

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#84]
Hangs for a long time (perhaps indefinitely) while trying to derive depth from these markers
```
['STARS', 'MARKERLESS', 'STARS', 'e', 'STARS', 'MARKERLESS', 'STARS', 'c', 'd', 'STARS', 'MARKERLESS', 'STARS', 'f', 'STARS', 'MARKERLESS', 'a', 'b', 'c', 'd', 'e', '* * *', 'MARKERLESS', 'STARS', 'MARKERLESS', 'STARS', 'g', 'h', '1', '2', '3', '4', '5', '6', '7', '8', 'i', 'ii', 'iii', '9', '10', '11', 'i', '1', '2', '3', '4', 'MARKERLESS', 'MARKERLESS', 'MARKERLESS', 'STARS', 'MARKERLESS', 'STARS', 'b', 'c', 'd', 'e', 'STARS', 'MARKERLESS', 'a', 'b', 'MARKERLESS']
```

I think this corresponds to https://www.federalregister.gov/articles/2014/03/27/2014-06778/importation-of-arms-ammunition-and-defense-articles-removal-of-certain-defense-articles-currently-on#p-55 . May be simplest just to break this up

**Comment by tadhg-ohiggins** [comment]
Adding the Choom! milestone to this to remind me to work on it, even though I'm not that confident that I'll find the answer in the next sprint.

**Comment by cmc333333** [comment]
18f/regulations-parser#130 makes this runnable. We could optimize it more, but it might make sense to close this issue out

**Comment by tadhg-ohiggins** [comment]
447 didn't seem to take too long to build for me with the new code, and I think we should close this out and make an optimization-specific issue if we want more speedups, since this was originally about 447 hanging indefinitely. BTW nice job figuring out a fix for this CM!
