### ISSUE TITLE
27 CFR 479, 555 definitions broken

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#85]
There's some unexpected interplay between the recent `EXTRACT` conversion and definitions. In particular, it seems that all definitions after the 479-11-p13 and 555-11-p34 are getting lost.

Found via (on 18f master)
```
eregs compare_to 27 479 https://[demo url]/api layer/terms
eregs compare_to 27 555 https://[demo url]/api layer/terms
```

**Comment by tadhg-ohiggins** [comment]
Fixed by https://github.com/18F/regulations-parser/pull/116

**Comment by cmc333333** [comment]
Fixed!
