### ISSUE TITLE
Update regulations-site frontend libs

### ISSUE THREAD

**Issue by cmc333333** [18F/atf-eregs#89]
From gemnasium results:

* backbone 1.0.0 -> 1.2.3
* htmlshiv 3.6.2 -> 3.7.2
* jquery 1.11.0 -> 2.1.4 (may need to stay in the 1.X line)
* respond 1.1.0 -> 1.4.2

Would be good to send these to CFPB (and/or pull in any updates they've made)

**Comment by jbarnicle** [comment]
The backbone upgrade to 1.2.3 breaks the current site - JS tests all pass.  Will investigate further.

**Comment by jbarnicle** [comment]
htmlshiv, jquery (1.11.3), and respond have been updated (awaiting PR).  The app will need to be updated to accommodate the Backbone upgrade - creating a separate issue for that.

**Comment by cmc333333** [comment]
Resolved by 18f/regulations-site#51
