### ISSUE TITLE
Add 555 intro text for reg 555

### ISSUE THREAD

**Issue by Journerdism** [18F/atf-eregs#95]
PART 555—COMMERCE IN EXPLOSIVES

Part 555 regulations relate to commerce in explosives.

The Regulation covers topics such as:

 Definitions; including definition of explosive materials

 Licensing and permit requirements

 Conduct of business by licensees and operations by permittees

 Storage of explosive materials

 Records and reports required of licensees and permittees

 Relief from disabilities

 Exemptions, unlawful acts, penalties, seizures, and forfeitures

 ATF Explosives Q&A 

 Explosives Forms - https://www.atf.gov/explosives/explosives-

forms?og_group_ref_target_id=196

 Explosives Publications - https://www.atf.gov/resource-center/publications-

library?search_api_views_fulltext=&field_document_type_1=All&og_group_ref=2&=Apply

(ORIGINAL FILE WITH FORMATTING: https://docs.google.com/a/gsa.gov/document/d/17abGthcEEOQ72EcsHYR-HtWjl8hBs8b5PxDmn7-qpFw/edit?usp=sharing)

**Comment by cmc333333** [comment]
@Journerdism can we push back a little bit on that intro text? It's a tad uninspired and certainly redundant

**Comment by cmc333333** [comment]
@Journerdism what do you think about just removing that line?

<img width="530" alt="screen shot 2015-12-14 at 11 40 59 am" src="https://cloud.githubusercontent.com/assets/326918/11786974/80690f62-a257-11e5-91e9-208b305519c0.png">

**Comment by Journerdism** [comment]
Sure, sounds good
