### ISSUE TITLE
Add 447 intro text for Reg 447

### ISSUE THREAD

**Issue by Journerdism** [18F/atf-eregs#96]
Title 27: Alcohol, Tobacco Products and Firearms

PART 447—Importation of Arms, Ammunition and Implements of War

Part 447 regulations relate to that portion of section 38 of the Arms Export Control Act of 1976, as amended, which is concerned with the importation of arms, ammunition and implements of war. 

The Regulation covers topics such as:

Definitions
United States Munitions Import List
Registration and permit requirements
Restrictions and exemptions
Penalties, seizures and forfeitures
Additional Resources

Arms Export Control Act--USC 22
Imports & Exports Q&A - https://www.atf.gov/qa-category/imports-exports 

========
ORIGINAL FORMATTING: https://docs.google.com/a/gsa.gov/document/d/17abGthcEEOQ72EcsHYR-HtWjl8hBs8b5PxDmn7-qpFw/edit?usp=sharing

**Comment by cmc333333** [comment]
Added to sprint as Tadhg's looking at getting a version of 447 up

**Comment by cmc333333** [comment]
Include a warning if the data isn't complete
