### ISSUE TITLE
Add 478 intro text to Reg 478

### ISSUE THREAD

**Issue by Journerdism** [18F/atf-eregs#97]
PART 478—COMMERCE IN FIREARMS AND AMMUNITION

Part 478 regulations relate to commerce in firearms and ammunition.

The Regulation covers topics such as:

Definitions; including firearms and ammunition
Licensing requirements
Conduct of business or activity by licensees
Records and reports required of licensees
Relief from disabilities
Exemptions

Additional Resources

Gun Control Act--USC 18, Chapter 44
Firearms Q&A 
Firearms Form - https://www.atf.gov/firearms/firearms-forms
Firearms Publications - https://www.atf.gov/resource-center/publications-library?search_api_views_fulltext=&field_document_type_1=All&og_group_ref=1&=Apply&field_document_type_value=All&og_group_ref_target_id=186

========
ORIGINAL FORMATTING: https://docs.google.com/a/gsa.gov/document/d/17abGthcEEOQ72EcsHYR-HtWjl8hBs8b5PxDmn7-qpFw/edit?usp=sharing

**Comment by cmc333333** [comment]
@Journerdism similar here; can we get/craft a better intro?

**Comment by Journerdism** [comment]
Sure, lemme see what they can do.

**Comment by cmc333333** [comment]
Done and done
